### ISSUE TITLE
Random notification saying I have a new message. 

### ISSUE THREAD

**Issue by medi0crescientist** [ccrama/Slide-iOS#100]
![img_0746](https://user-images.githubusercontent.com/30246837/28493256-f10646dc-6ed8-11e7-9027-16e2fe3bb11e.PNG)

**Comment by jglass071** [comment]
![img_0435](https://user-images.githubusercontent.com/18504622/28544323-aad18d96-70ba-11e7-825a-38a331c2efbb.PNG)

I also got one of these on alpha 1 although haven’t checked the second one, as I disabled background app refresh.

**Comment by ccrama** [comment]
That has been removed, it was some test code
