### ISSUE TITLE
Crashes when visiting Support Slide menu

### ISSUE THREAD

**Issue by Fayette3001** [ccrama/Slide-iOS#1009]
When in the Settings and going to the Support Slide tab the entire app crashes after a few seconds. 
[Slide for Reddit Pro Crash.zip](https://github.com/ccrama/Slide-iOS/files/4630367/Slide.for.Reddit.Pro.Crash.zip)

**Comment by ccrama** [comment]
I've fixed that for the next update, thank you for the report!
