### ISSUE TITLE
Comment sort order only applies to first page of comments 

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#1011]
The first page of comments sort as desired, but subsequent pages seem to sort as hot. 

Steps to reproduce:
- Find a very active post and sort comments by new (for example something related to a current event)
- Scroll to end of comments and note the time of the oldest post (7 minutes in my case)
- Press load more - the first post loaded in the next batch will be out of sequence (2 hours in my case)

**Comment by ccrama** [comment]
Fixed, along with #1177 with 888e891f!
