### ISSUE TITLE
Title cut off

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#102]
I think I've had this issue before but...

Front-page view
![img_1826](https://user-images.githubusercontent.com/30244311/28497185-06d2c32a-6f36-11e7-8d00-c913f61b6b1b.PNG)

Expanded (W/ comments section)
![img_1827](https://user-images.githubusercontent.com/30244311/28497187-06e5ce70-6f36-11e7-8755-2b0c124af32a.PNG)

But here's how it's displayed in Narwhal:
![img_1825](https://user-images.githubusercontent.com/30244311/28497192-155962f0-6f36-11e7-9c97-e772b8e510bc.PNG)

**Comment by ccrama** [comment]
Should be fixed in Alpha 2
