### ISSUE TITLE
Crash when going to most subreddits

### ISSUE THREAD

**Issue by laserstrike** [ccrama/Slide-iOS#104]
all, food, funny, gifs maybe some others work. 

but slide_ios, music, announcements, movies & more do not.

sorry I'm not sure what exactly is causing it. I tried guest mode and deleting and reinstalling, but no go. should I also create a thread for this on the subreddit? to see if others have this issue? or should I keep it to GitHub?

**Comment by laserstrike** [comment]
oh, yea. this is on alpha 2.

**Comment by ccrama** [comment]
How are you accessing these subreddits?

**Comment by ccrama** [comment]
Pushed an update to fix it, hopefully it arrives soon

**Comment by laserstrike** [comment]
ok cool. but just so you know, it was both entering them and selecting them from the um, drawer I think it's called.
