### ISSUE TITLE
v.redd.it videos are not filtered correctly through the Content Hiding system

### ISSUE THREAD

**Issue by Verbina29** [ccrama/Slide-iOS#1053]
![1B41330D-5FC2-4FB3-9DF8-20E479B7EFAC](https://user-images.githubusercontent.com/15861936/89496170-78756780-d77f-11ea-861c-fc9ff7bad167.png)
![C0891406-D820-404E-BE30-498A977ACED2](https://user-images.githubusercontent.com/15861936/89496176-7ad7c180-d77f-11ea-8c38-88382cf3a14a.png)
![B1F418C5-A711-420F-B28F-58594EC2E06C](https://user-images.githubusercontent.com/15861936/89496181-7c08ee80-d77f-11ea-9f03-a9e6c580b3f2.png)
![28661D3B-44D1-4A94-B9C4-3B6B35AE7B2F](https://user-images.githubusercontent.com/15861936/89496182-7ca18500-d77f-11ea-84c1-958c0fab801a.png)
![57BDF7F4-9929-4617-8232-29D98FABDE84](https://user-images.githubusercontent.com/15861936/89496185-7d3a1b80-d77f-11ea-9eea-6e0b126cf896.png)
As you can see from these screenshots, filters of all kinds don’t function in any way, shape, or form. Not in multireddits, and not in regular subreddits. I am using an iPhone 8 with iOS 13.6, Slide TestFlight version 5.4, build 170.

**Comment by ccrama** [comment]
Hello! The domain should v.redd.it not v.reddit.com. Reddit Videos are considered "gifs" in app, although I'll add that to the filtering list for videos as well. Enabling either of those filters should work for you
