### ISSUE TITLE
Add "are you sure" message when unsubscribing from sub

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#107]
I'm on the iPad; not sure if this is applicable to iPhone. 

The add/remove sub button is right by the close comment button on the comments pop up window. It would be nice if there was a warning prior to unsubscribing from a sub.

**Comment by incIined** [comment]
Or an option to turn off the unsubscribe button. Never have I needed to quickly unsubscribe from a sub.

**Comment by ccrama** [comment]
Yeah might just make it not there if you are not subscribed

**Comment by jglass071** [comment]
Yeah I accidentally pressed that just now not realising what it was. Definitely would be useful for subscribing but probably not unsubscribing.

**Comment by ccrama** [comment]
Done!
