### ISSUE TITLE
In the Gestures settings menu, gestures is spelled “gesutres”.

### ISSUE THREAD

**Issue by Verbina29** [ccrama/Slide-iOS#1074]
![4C45E9CF-A0BF-4C7D-9B3F-ABB12DE8FBCF](https://user-images.githubusercontent.com/15861936/90990088-1f217c80-e564-11ea-9312-7acd2c0679e3.jpeg)

**Comment by ccrama** [comment]
Thakns for the report 😉

Fixed!
