### ISSUE TITLE
Adjust popup behavior for iPad

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#1087]
https://www.reddit.com/r/slide_ios_beta/comments/is0ncj/build_182_bug_fixes_ios_14_widgets_and_more/g568tr5?utm_source=share&utm_medium=web2x&context=3

https://www.reddit.com/r/slide_ios/comments/ins8fj/question_is_there_a_way_to_view_this_tab_in/

Users don't seem to like the popup behavior on iPad. Is this something we can adjust?

**Comment by ccrama** [comment]
I have done this for "single mode", I don't think it would vibe well with multi-column mode on iPad
