### ISSUE TITLE
Swipeable subreddit bar option resets after closing app

### ISSUE THREAD

**Issue by Verbina29** [ccrama/Slide-iOS#1091]
![D4798B0B-820D-4F4F-92A3-8AC2BD556EFA](https://user-images.githubusercontent.com/15861936/93386096-cc6a7600-f82c-11ea-8397-f0cbbe24cd6b.png)
![58F19564-9D8A-40EE-B643-813212E03033](https://user-images.githubusercontent.com/15861936/93386099-cd9ba300-f82c-11ea-80b7-8630013d6485.png)
Closing the app after disabling the swipeable subreddit bar option reenables the option.
Using Slide version 5.4 build 183 on an iPhone 8 on iOS 13.7

**Comment by ccrama** [comment]
That option actually does not exist any more, but I may add an option to only show one subreddit at a time in the header if enabled. Looking into this for the v6 release!

**Comment by ccrama** [comment]
Fixed with b35d73e26c187a4b2d2e798a71f0ff435d56a9a2
