### ISSUE TITLE
Widget improvements for 6.0

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#1095]
- [x] Right now the widgets show rectangles instead of data when browsing widgets in the iOS home screen "wiggle mode". This is meant for the case where a widget is added but not populated yet. We should use actual fake data in wiggle mode so the user knows what the widget will look like.
- [x] "frontpage" does not work with the hot posts widget.

**Comment by ccrama** [comment]
Got it done with Live data!
