### ISSUE TITLE
"Clear cache" crash and potential improvements

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#1100]
Crash here when clearing cache:
<img width="2560" alt="Screen Shot 2020-09-18 at 4 43 53 PM" src="https://user-images.githubusercontent.com/702432/93643522-248cae00-f9ce-11ea-9567-6f0a99e9ca44.png">

Also, if this is an async operation, we should show a popover that tells us it's erasing things so that we can't click anything else and crash.

**Comment by ccrama** [comment]
Done and done!
