### ISSUE TITLE
Inconsitent header coloring

### ISSUE THREAD

**Issue by matty1086** [ccrama/Slide-iOS#1105]
The header bar on the last few test flight builds has inconsistent theming. The subreddit names are surrounded with a white (or dark, if dark theme enabled) box most times, however, sometimes - though not always - when returning to the app from the home screen the primary color is replaced with all white. Swiping to another sub brings back the inconsistencies.

I figure a video is easier to see the behavior. I forget which test flight builds this started in but can confirm still there in the latest. I've also included a screenshot of my theme settings.

https://imgur.com/a/p4Yh4dS

iPhone SE 2020, iOS 14.0.1
Slide v6 build 187

**Comment by ccrama** [comment]
Has been fixed for the final build, thank you for the report!
