### ISSUE TITLE
Add option to swap long/short press behavior on comments

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#111]
I think this was is an option on the Android version. 

By default, tapping a comment collapses the child comments and long pressing brings up the comment options (upvote/downvote/etc). It would be nice if we could swap this behavior so long pressing a comment collapses the children.

**Comment by ccrama** [comment]
Yeah it was an option in the android version. The groundwork is coded there already, just have to add a setting item for it!

**Comment by ccrama** [comment]
Done!
