### ISSUE TITLE
Unbearably slow loading times.

### ISSUE THREAD

**Issue by verbina29** [ccrama/Slide-iOS#1117]
It takes 30 seconds to load all of a sudden. Tried updating phone, deleting and reinstalling app, turning phone off all the way and then back on, clearing cache, clearing post and subreddit history.
iPhone 8, iOS 14.1, Slide 6.0.8 build 205.

**Comment by verbina29** [comment]
Wait, now it’s not doing it. Weird.

**Comment by ccrama** [comment]
Are you still able to reproduce this?

**Comment by verbina29** [comment]
Nope.

**Comment by ccrama** [comment]
Feel free to re-open if needed
