### ISSUE TITLE
Cosmetic request: Add option to disable rounded corners on post thumbnails

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#112]

**Comment by ccrama** [comment]
I think that might be too niche of an option, any reason in particular?

**Comment by WickedColdfront** [comment]
With "card mode" disabled the post corners are square and I think it'd look better if the thumbnail corners matched. Maybe you make it so the thumbnail corners are square when card mode is off and they're round when card mode is on?

http://imgur.com/a/2Vdx4

**Comment by ccrama** [comment]
Done with 8687c9d2c9028a910a6f31e2adf1a4ed67c3895a
