### ISSUE TITLE
Cosmetic: Add option to change transparency of iOS status bar. 

### ISSUE THREAD

**Issue by medi0crescientist** [ccrama/Slide-iOS#113]
The status bar is better in build 2, but it's still kind of messy. It would be nice if we had the option to make it darker.

**Comment by medi0crescientist** [comment]
Or have the status bar match the color of the subreddit theme? That would look really nice.

**Comment by ccrama** [comment]
Like the color that it is whenever the toolbar is shown?

**Comment by medi0crescientist** [comment]
Yup! I think that would look great.

**Comment by ccrama** [comment]
Now the bar has been totally removed
