### ISSUE TITLE
Read Later view - Read Later button opens moderation menu

### ISSUE THREAD

**Issue by MartnPoef** [ccrama/Slide-iOS#1147]
In the Read Later post view the Read Later button opens the Moderation menu instead of removing the post.
![136A654D-56FB-43CA-8E43-DDEB5BE8C639](https://user-images.githubusercontent.com/791194/102689429-534d3700-41fe-11eb-8feb-3e65c2f161b4.png)

**Comment by cocoelacanth** [comment]
I'm having virtually the same issue, but it affects the Save button rather than the Read Later button.

For some extra info, this occurs spontaneously on subreddits I don't moderate. Sometimes the button works properly, and sometimes it doesn't. This issue is app-wide.

**Comment by ccrama** [comment]
@CocoTheMii have you tried out the v7 TestFlight builds? I believe both of these issues have been addressed as of Build 220

**Comment by cocoelacanth** [comment]
@ccrama The issue does seem to be fixed now. I'm running Build 221 and I haven't seen this bug in a while.

**Comment by MartnPoef** [comment]
This is fixed for me in public Slide v7.0.0.
