### ISSUE TITLE
False positive in YouTube video detection

### ISSUE THREAD

**Issue by LMLB** [ccrama/Slide-iOS#1148]
Looks like links that have `youtu` anywhere in the URL are treated as YouTube videos. I have encountered this in both posts and comments.

[Here is an affected post](https://reddit.com/r/technology/comments/kcweqy/gmail_google_and_youtube_down_services_crash_for/). You can also search for `youtube` on [r/technology](http://www.reddit.com/r/technology) to find many more.

I think it's caused by the last part of this line:

https://github.com/ccrama/Slide-iOS/blob/48684c8a10c4d581639ec7ba4ae90e12a2226775/Slide%20for%20Reddit/ContentType.swift#L148

**Comment by ccrama** [comment]
Thank you for the report! You were right about that line, I've fixed it in #1139 and the fix will be out in the next v7 TestFlight
