### ISSUE TITLE
Cannot save videos.

### ISSUE THREAD

**Issue by jphilll** [ccrama/Slide-iOS#1150]
I cannot save videos unless I give the app the permission to access all of my photos, while there are other apps that don’t need such permission to do so. Why?

iOS version: 14.3
App version: latest

**Comment by colejd** [comment]
Perhaps you've already given those apps permission? App developers need permission to access your camera roll, no exceptions.

**Comment by jphilll** [comment]
Well, let me take the _Apollo_ app(another reddit client) as an example. It only needs the permission to _Add Photos Only_, but I can save photos and videos in the app. 

[Apollo Permissions](https://imgur.com/gallery/90JBDRN)

**Comment by colejd** [comment]
Ahhh. I see. We ask for permission for writing to _and reading from_ the camera roll, as we have a built-in Imgur uploader you can use while writing posts. There's a separate way we can ask for just permission to write without reading, which I think we can do. Thanks for bringing it to our attention @jphilll! For now, if you're comfortable with it, you can limit photo access to "only selected photos" and just not select anything.

**Comment by colejd** [comment]
@ccrama, we should use `UISaveVideoAtPathToSavedPhotosAlbum(_:_:_:_:)` when saving videos. From [the docs](https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/requesting_authorization_for_media_capture_on_ios):
> If your app needs only to save movie files to the Photos library, the UISaveVideoAtPathToSavedPhotosAlbum(_:_:_:_:) function provides a simpler alternative to PHPhotoLibrary. This function requires only write access to the library, so use the NSPhotoLibraryAddUsageDescription key in your Info.plist to provide a message to the user when asking for permission to save to the Photos library.

This would let us save to the camera roll without requesting read access.

**Comment by jphilll** [comment]
Cool, man! I'm happy to help making _Slide_ better and hoping to see a new version soon!

**Comment by ccrama** [comment]
Done in f3f739c6! Thank you for the suggestion!
