### ISSUE TITLE
Erratic behavior when reaching last post in multi-column mode

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#116]
When reaching the last post in a subreddit the last post is not completely visible (post action bar is off the screen) and the post list vertically shakes. 

Can reproduce by going to /r/slide_ios and scrolling to the last post.

**Comment by ccrama** [comment]
Is this when it is loading more?

**Comment by WickedColdfront** [comment]
No, just when you reach the end of the post list.

**Comment by ccrama** [comment]
Fixed for Alpha 4! (also made them spread out more evenly...)
