### ISSUE TITLE
App doesn't show updated flairs / No flair on AskOuija subreddit

### ISSUE THREAD

**Issue by AnsgarH1** [ccrama/Slide-iOS#1160]
In the [AskOuija subreddit](reddit.com/r/AskOuija), People can ask funny questions, and redditors can comment only a single character as answer. The answers on comments will build a word, wich through the hive-mind of reddit is usually a funny answer.

Each hour the AskOuija bot on the subreddit updates the posts flair with the most liked answer. 

The Problem I have, is that the Slide iOS App dosn't show the flair. Other flairs are shown fine, but it has probably something todo, with updated flairs. The Problem occurs both on my iPhone (iPhone 12 Standard running iOS 14.4. and Slide Version 7 build 223) and my iPad (2019 10.2-inch running the same software versions). I also tested it on a Samsung Note 7 running Slide v6.6.1-4 where it is working fine, so it seems to only exist on the iOS App.

Here are some Screenshots comparing the Issue to the official Reddit App:

![IMG_0380](https://user-images.githubusercontent.com/46782109/108391359-ecee9000-7211-11eb-9bf0-624bf6e49396.PNG)
![IMG_0381](https://user-images.githubusercontent.com/46782109/108391364-ee1fbd00-7211-11eb-9f53-3525428daf88.PNG)
![IMG_0382](https://user-images.githubusercontent.com/46782109/108391369-ef50ea00-7211-11eb-8ece-9f265f1e9fd9.PNG)

**Comment by ccrama** [comment]
I believe the issue is with subreddits that haven't adopted Reddit's "new" flair system. Will add support for this in 7.0.2! Thank you for the very detailed bug report.
