### ISSUE TITLE
[Feature Request] - Regex Patterns for filtering

### ISSUE THREAD

**Issue by ondrovic** [ccrama/Slide-iOS#1175]
Would love to see the ability to use regex patterns in the filtering, would make it easier to filter out content.

Examples:
filter to exclude items that have one or two digits in the title
`(\b\d\b|\b\d{2}\b)`

filter to exclude items that are surround by [] - [EXAMPLE], [10], [etc]
`\[\w.+\]`

**Comment by ondrovic** [comment]
so I think I may have come up with a solution to this, I am not very good at swift, or have an apple developer account but did test it locally and it seemed to work. Maybe some who is a bit better can take it an polish it a bit.

I made the following function
```
public static func patternMatched(_ array: [NSString], value: String) -> Bool {
        for text in array {
            let regex = try! NSRegularExpression(pattern: String(text), options: NSRegularExpression.Options.caseInsensitive)
            let matches = regex.matches(in: value, options: [], range: NSRange(location: 0, length: value.length))
            
            if !matches.isEmpty {
                return true
            }
        }
        
        return false
    }
```

then used it like this as an example

`patternMatched(PostFilter.titles, value: link.title)`

I have attached the whole modified file PostFilter.swift this was only done for Slide For Reddit so it may need to be applied to the other projects, applied for title, htmlBody, flairs

[PostFilter.zip](https://github.com/ccrama/Slide-iOS/files/6135295/PostFilter.zip)

**Comment by ccrama** [comment]
Good stuff, thank you for the detailed post and code! I abstracted the logic out a little bit so that the function could be used elsewhere, but I used parts of your solution in https://github.com/ccrama/Slide-iOS/commit/2e38f4d45cbc477c2f55dc95c2730a2dade89f02#diff-612caacac62a32d8c8373caa792fac4d39710cae4349a5e974a59b26a0362640R57. 

It works great, will be shipping this with v7.1!
