### ISSUE TITLE
Load more comments button does not respect the sorting mode

### ISSUE THREAD

**Issue by superrnovae** [ccrama/Slide-iOS#1177]
It's kinda annoying, last time I checked it was still borked on beta version. Afaik it also does that on android version too.    

Steps to reproduce:   
 1. Open a post that has its comments sorted by new.  
 2. Scroll to the bottom (last loaded comment).  
 3. Tap on 'Load x more' button.   
 
Expected behaviour: more comments are loaded and they are sorted by new, therefore respecting post's sorting mode.   

Actual behaviour: more comments are loaded and they are sorted by top.   

Another way to reproduce:   
 1. Open any post.  
 2. Change comment sorting to anything that isn't 'by top'.  
 3. Tap on 'Load x more' button on the bottom.   
 
Expected behaviour: loaded comments respect currently set sorting mode. 

Actual behaviour: loaded comments are sorted by top.   
   
Slide version: 7.0.2 build 225

Same issue [here](https://github.com/ccrama/Slide-iOS/issues/1011)

**Comment by ccrama** [comment]
Fixed in 888e891f, thank you for the report and detailed reproduction steps!
