### ISSUE TITLE
App theme switch does not apply to all parts of the UI

### ISSUE THREAD

**Issue by superrnovae** [ccrama/Slide-iOS#1178]
When I change the theme of the application, some parts of the UI are left unaffected. 

How to reproduce:    
 1. Turn on the night theme switch.  
 2. Swipe to sidebar.  
   
Here is how it looks like [image](https://user-images.githubusercontent.com/57127875/111089700-3d18f380-852d-11eb-8cdc-cf77597ab2bf.png).  
      
Edit: sidebar background color is correct after switching to another app and opening back slide, but icons are black instead of white. The issue goes away after completely closing and relaunching the application.

**Comment by ccrama** [comment]
This has been fixed in the mac_catalyst branch, I switched to an "event-driven" settings change model, where changes are listened to by each component and reacted to when changed! This branch will be released as 7.0.3 or 7.1
