### ISSUE TITLE
Disable new post/hide viewed posts FAB

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#118]
This one: 
![img_1845](https://user-images.githubusercontent.com/30244311/28510352-c5e8a812-6ffc-11e7-806d-2fe3c82e986e.PNG)

Would be nice to have an option to have either as well, as I'd like only the new post FAB and not the hide viewed FAB. 

Also, the animation to bring it up when scrolling up could be improved.

**Comment by ccrama** [comment]
Same as #57
