### ISSUE TITLE
Slide to go back gesture doesn't follow finger 

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#119]
https://streamable.com/pxzf3

First client is Narwhal, the second is Slide. Bonus crash at the end.

**Comment by ccrama** [comment]
I did that on purpose in Slide, it’s just a different way of doing it

**Comment by lnkcrb82r3z2g4** [comment]
I think back gesture would fit better with iOS if it behaved the same as in stock apps like settings and the app store. But if you prefer to keep the gesture as is, maybe only return to the previous page after the user's finger lifts off the screen. The back transition is very sudden currently.

**Comment by rebel1804** [comment]
This is nice behavior when swiping right from the middle of the screen, but did catch me off guard when swiping from the edge of the screen.

**Comment by rebel1804** [comment]
Actually, upon further usage, I found myself accidentally triggering this action when scrolling. Maybe make it less sensitive or impossible during scrolling?

**Comment by ccrama** [comment]
Different system now
