### ISSUE TITLE
Tracking - app-measurement.com

### ISSUE THREAD

**Issue by deroverda** [ccrama/Slide-iOS#1194]
Hi, 
It looks like the Slide app is constantly sending requests to the above address. Several hundreds of requests every day ... 

app-measurement.com is owned by google. This domain is used by Google Analytics for Firebase to report the analytics events from the client. Is this the case that Slide uses this domain?

**Comment by colejd** [comment]
That's very odd. Slide doesn't use any analytics, and I'm pretty sure it doesn't use Firebase at all either. Maybe one of the dependencies snuck something in?

**Comment by deroverda** [comment]
@colejd thanks for replying. I guess it must be another app then. Glad to hear Slide doesn't use any analytics. Does it use any tracking at all? I know the official Reddit app is bloated with analytics and tracking.

**Comment by colejd** [comment]
There is no tracking in the app. Makes it really hard to track down bugs, lol

**Comment by deroverda** [comment]
Okay my bad then. Thanks for the info. Someone can close this now. I can't close it while using the GitHub app.
