### ISSUE TITLE
Menu options in comment bar disappeared (visually)

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#120]
![img_1860](https://user-images.githubusercontent.com/30244311/28518352-6d7f9bc0-701c-11e7-8be5-4d41b57b6cd8.PNG)

Can still be accessed if I click on the left edge though.

**Comment by ccrama** [comment]
What device are you on? I set it to divide between 375px, which might be too big for your device

**Comment by incIined** [comment]
iPhone SE

**Comment by ccrama** [comment]
That explains it

**Comment by ccrama** [comment]
Fixed
