### ISSUE TITLE
Visual glitches when changing some options

### ISSUE THREAD

**Issue by jglass071** [ccrama/Slide-iOS#121]
After changing some options - can’t remember exactly but I know that “hide post button” and “use subreddit tabs” were two - various visual problems appeared.
![img_0477](https://user-images.githubusercontent.com/18504622/28541780-18b3d03e-70b2-11e7-9cd8-607c7fadb633.PNG)
App restart fixed it.

**Comment by ccrama** [comment]
Should no longer be an issue
