### ISSUE TITLE
(Suggestion/Bug) Option to keep menu pinned to top of screen

### ISSUE THREAD

**Issue by jglass071** [ccrama/Slide-iOS#124]
Currently it can be difficult to access (there has to be no scrolling at all if you want to slide out the menu and sliding it out doesn’t work at all if the app is in SlideOver/multitasking. The menu also disappears when scrolling right to the top and to get it back I need to scroll down and back up again - not sure if this is intended or a bug.

**Comment by ccrama** [comment]
This should no longer be needed with the new menu system
