### ISSUE TITLE
(Suggestion) Tap outside of comments view on iPad to return to the subreddit

### ISSUE THREAD

**Issue by jglass071** [ccrama/Slide-iOS#128]
A tap outside of the comments view / on the posts in the background would act as if the user had pressed the X button in the title bar. Makes the app a little easier to use but should be an option as some people might accidentally press it. (Or make it double/triple tap)

**Comment by jglass071** [comment]
Or tap to close in other areas of the app as well such as images. Useful on iPad because the size of the screen can make it difficult to reach for the close icon or swipe

**Comment by WickedColdfront** [comment]
I think this is a good idea, but I don't think it should be an option - it should be default. 

This approach fits much better with what users expect when using iOS and would match the design model of built in apps such as the App Store and iOS folders.

**Comment by ccrama** [comment]
Interestingly enough, this design is quite difficult to do because Apple explicitly doesn't allow gesture detection outside of a modally-displayed view such as comments

**Comment by ccrama** [comment]
Done for next alpha
