### ISSUE TITLE
Media Views Overhaul

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide-iOS#129]
- [x] New MediaDisplay VC which can load video or image content
- [x] ViewController using new MediaDisplay VC
- [x] Toolbar with count and exit
- [x] Offset content if toolbar is present
- [x] Share button on toolbar of Album view
- [x] HQ integrate on MediaDisplay VC
- [x] Keep videos from showing black background
- [x] Tap to show video controls
- [x] "T" icon to show album text if it exists
- [ ] Overview system

**Comment by rebel1804** [comment]
Those features sound great, an overview especially. Also add the swipe right to exit on albums?

**Comment by ccrama** [comment]
Yes

**Comment by ccrama** [comment]
- [ ] ViewController using new MediaDisplay VC
- [ ] Toolbar with count and exit
- [ ] Share button on toolbar of Album view
- [ ] HQ integrate on MediaDisplay VC
- [ ] Keep videos from showing black background
- [ ] Tap to show video controls
- [ ] "T" icon to show album text if it exists
- [ ] Overview system
