### ISSUE TITLE
In guest mode, cannot search all or within subreddits

### ISSUE THREAD

**Issue by laserstrike** [ccrama/Slide-iOS#131]
The loading animation just keeps on spinning. 

No results show up.

**Comment by laserstrike** [comment]
And even when logged in, nothing happens when tapping search in a subreddit one is not subscribed to. For example: Be logged in, go to subreddit you are not subscribed to (in my case r/Funny) and tap search: Nothing happens.

**Comment by ccrama** [comment]
Fixed
