### ISSUE TITLE
Suggestion: Add hamburger, sort, and "more" menus to subreddit carousel and remove subreddit title bar

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#133]
It's can be kind of jarring when you scroll up/down and the subreddit title shows or hides.  I think it might make more sense to add the buttons that are on the subreddit menu to the left/right of the subreddit carousel and just have them show up all the time.  That would also save users a step when they want to access additional menu options or change sorting - instead of scrolling down first, they can just click the button.

**Comment by ccrama** [comment]
Totally new system now in the next alpha, the sub chooser is down at the bottom!
