### ISSUE TITLE
Can't exit this page without closing the app. 

### ISSUE THREAD

**Issue by medi0crescientist** [ccrama/Slide-iOS#136]
![img_0848](https://user-images.githubusercontent.com/30246837/28873611-65bb4956-775c-11e7-8235-e874deb85c67.PNG)

**Comment by ccrama** [comment]
You can swipe from anywhere  to exit that

**Comment by medi0crescientist** [comment]
Swiping wasn't working for me when this happened.

**Comment by ccrama** [comment]
It's now embedded in the new media view (not relevant anymore)
