### ISSUE TITLE
More consistent up vote/down vote pattern

### ISSUE THREAD

**Issue by laserstrike** [ccrama/Slide-iOS#141]
On a post the alignment is upvote downvote. With a comment it's downvote upvote. 

Could they both be the same for consistency? I think upvote downvote looks better in general, but I'm no expert. Is it the same with slide on Android?

**Comment by WickedColdfront** [comment]
I noticed the same thing - I think this is a Duplicate of #117 

I agree that upvote/downvote is the right order, as this would match the native Reddit app.

**Comment by laserstrike** [comment]
Crap. You're right. Please close.
