### ISSUE TITLE
Extra padding on some posts

### ISSUE THREAD

**Issue by laserstrike** [ccrama/Slide-iOS#145]
Latest alpha. This happens with card mode, crop big pic and center lead image activated. ![Image](http://i.imgur.com/VeBHFM8.jpg) For some reason, there's a bit of extra padding going on, and I don't know why.

**Comment by ccrama** [comment]
It is because I have to create code to estimate the height based on text length and image height quickly without causing lag. I have done some improvements on this in Alpha 3, which should fix your issue!
