### ISSUE TITLE
Subreddit name cutting off first post.

### ISSUE THREAD

**Issue by medi0crescientist** [ccrama/Slide-iOS#147]
![img_0900](https://user-images.githubusercontent.com/30246837/29824145-4a874438-8c96-11e7-82ee-719025e3f1b9.PNG)

**Comment by medi0crescientist** [comment]
Also happens in posts. 
![img_0901](https://user-images.githubusercontent.com/30246837/29827743-d0ee0ab8-8ca8-11e7-805b-ef64f31f9200.PNG)

**Comment by ccrama** [comment]
Hmm I’m not seeing that. What device are you on?

**Comment by medi0crescientist** [comment]
7+

**Comment by OrionDB5** [comment]
It also happens on my iPhone 7 running iOS 10.3.3, latest alpha (0.3) from TestFlight

**Comment by ccrama** [comment]
Not seeing it on my iPad or 6s, wonder if it's just something occurring on the 7

**Comment by OrionDB5** [comment]
Correct me if I'm wrong (I have no experience in programming apps for iOS) but isn't it strange to be related to iPhone 7 as it has the same display size as the 6s? If you are on the iOS 11 beta maybe it could be that.

**Comment by laserstrike** [comment]
I'm on iPhone 7 with 10.3.3 and can confirm this issue.

**Comment by ccrama** [comment]
Yes it is strange @OrionDB5 , which is why I'm looking for something the devices have in common. It had too much padding on my device after the XCode update and the latest developer build of iOS 11, so I removed the extra padding which made it cut off on some devices

**Comment by incIined** [comment]
Same issue on SE, 10.3.

**Comment by ccrama** [comment]
Should be fixed now
