### ISSUE TITLE
(Alpha 3) Lots of crashes in top-right actions menu

### ISSUE THREAD

**Issue by jglass071** [ccrama/Slide-iOS#149]
**In the menu in the top right, the following menu items entirely crash the app:**
- Sidebar
- Subreddit theme
- Base theme

The menu also appears in the wrong place.

Refresh in the menu doesn’t work (does nothing) and pulling to refresh in a subreddit crashes Slide.
Post sorting (the three line menu in the top right) also crashes the app.

Edit: iPad Pro 9.7 iOS 11

![b7a5ca88-94d9-434f-9c8b-e0b66037a6ca](https://user-images.githubusercontent.com/18504622/29894606-cfe06e42-8dcd-11e7-98e7-dbf8accf9be5.png)

**Comment by ccrama** [comment]
Should mostly be fixed for next alpha!
