### ISSUE TITLE
(Alpha 3) Tabs cut off in inbox

### ISSUE THREAD

**Issue by jglass071** [ccrama/Slide-iOS#150]
![c055fa1b-141a-4224-a605-d0fd71f5d41b](https://user-images.githubusercontent.com/18504622/29894839-cc1b1950-8dce-11e7-819c-0ed285153f89.jpeg)

iPad Pro 9.7
iOS 11 Beta 8

**Comment by ccrama** [comment]
Completely new menu in next alpha
