### ISSUE TITLE
When in Split-View multitasking, swiping out of a post causes the app to show a grey screen

### ISSUE THREAD

**Issue by jglass071** [ccrama/Slide-iOS#151]
![358cf0db-ad2e-448c-9f28-6f56fcc2754c](https://user-images.githubusercontent.com/18504622/29895130-e47d8842-8dcf-11e7-8346-40c417a412a4.jpeg)

This happens whenever Slide is in Split View set to occupy 25% of the screen. After removing Slide from Split View and re-adding it via the dock it is still entirely grey as in the screenshot above, same as before, and I need to force close using the app switcher to fix it (but it is fine in full screen mode even without doing this).

When the app is in this state the close button in the top action bar also doesn’t work however other buttons do. After pressing search in the top bar, the close button still does not work.

**Comment by ccrama** [comment]
Does this happen with multi-column mode disabled on your iPad?

**Comment by jglass071** [comment]
Yes, with the option disabled the issue still occurs. Swiping back still causes the grey screen and the close button does not work at all. It is the exact same behaviour as if multi column mode were enabled.

**Comment by ccrama** [comment]
Should no longer be an issue in Alpha 4!
