### ISSUE TITLE
Title cut off (Alpha 3)

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#152]
![img_2617](https://user-images.githubusercontent.com/30244311/30035052-d74c7398-915a-11e7-8e28-67db0e3f445d.PNG)

![img_2618](https://user-images.githubusercontent.com/30244311/30035051-d0da2866-915a-11e7-80c7-c766d2c3e567.PNG)

Narwhal:
![img_2619](https://user-images.githubusercontent.com/30244311/30035058-f0e1b778-915a-11e7-97a6-7679d2c81486.PNG)

Link to thread: https://reddit.com/r/WritingPrompts/comments/6xzkpm/wp_a_cult_summons_an_elder_horror_only_to_find/

**Comment by ccrama** [comment]
Should be fixed now!
