### ISSUE TITLE
Some threads don't show full title by random chance, crashing during navigation (3.0)

### ISSUE THREAD

**Issue by wowns106** [ccrama/Slide-iOS#153]
first of all i want to say that the ui is better than any iOS reddit clients. I even tried the sync beta and this easily beats it even at this stage. However, as said in the title, there are issues at Alpha.

Some threads with ridiculously long title will show without any problem, but sometimes a title that barely goes over two lines will be cut off. This occurs most frequently at /r/Askreddit, from what I've observed, but all other subreddits also reflected this issue.

Additionally, when using the comment navigator, sometimes when I press the down arrow, it will stop scrolling between the first comment and the second comment (somewhere in the middle), and when I press the up arrow after it stops in the middle, the app crashes immediately.

The tabs in profile (overall/submissions/comments/etc) doesn't work, althought swiping left to right works flawlessly.

I'm sure someone else had mentioned the swiping from right to left triggering left to right menu, so didn't include in the title, but writing it here just it case.

Also, this is personal preference but the subreddit tab in the bottom feels a bit unnatural. I would personally prefer it to be under the top menu bar.

Thank you for developing this app, you're making switching to apple a whole lot easier. I'm already using it as my daily driver. So wanted to show my appreciation by letting you know of the issues. cheers.

**Comment by ccrama** [comment]
Should both be fixed for the next alpha!
