### ISSUE TITLE
iPhone X safe area support and a few other issues

### ISSUE THREAD

**Issue by derek1906** [ccrama/Slide-iOS#174]
- Currently buttons are too close to the top and bottom edge which often overlap with the home bar and time/status icons.
- The main list view is clipped into the top nav bar when first started.
- The bottom “prev/next top comment” bar does not go away when going back from the comments.

**Comment by ccrama** [comment]
Would it be possible to include screenshots of issues 1 and 2? Currently don't have an X to do testing on

**Comment by derek1906** [comment]
I have created an [imgur album](https://imgur.com/a/UpH0l) with descriptions.

**Comment by ccrama** [comment]
Have consolidated to 

#178 
#176 
#177
