### ISSUE TITLE
Inline Tables

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide-iOS#18]
Parse and display tables from content in a horizontally scrolling view (like the table system in Slide Android)

**Comment by ccrama** [comment]
Interesting, that sounds like a way to implement it that is sort of a short cut (because it's much easier to implement), but if it works that would be great. Do you mind attaching a screenshot of how it displays this content?

**Comment by derek1906** [comment]
Here’s a screenshot of how it looks in Apollo: https://imgur.com/a/RJhyC0l

Apollo provides two views, where one is the normal horizontal scroll view (not optimal if it has a lot of columns), and one is the “list of lists” view (not optimal if the cells require to be at specific locations).

**Comment by ccrama** [comment]
Oh interesting, that is actually loads easier to implement than what I was envisioning for this issue. Will add this in for the next update!

**Comment by ccrama** [comment]
Done and done!

**Comment by ccrama** [comment]
Nevermind, after over a weekend of work I actually implemented it the correct way :P
