### ISSUE TITLE
Blur NSFW images?

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide-iOS#182]
Need some feedback on this, might also implement on Android

**Comment by incIined** [comment]
I'm down with this idea.

**Comment by Kazbin** [comment]
Would say, if you implement it, definitely make it optional in the settings... maybe just an opt-out

**Comment by nalexander50** [comment]
I think it's an important feature. Not only for actual NSFW content but also for spoiler content. I'd be open to looking into the iOS implementation.

**Comment by ccrama** [comment]
If someone does go about implementing it, Reddit already includes this image in the json data. Wouldn't be hard to add a variable to the Realm wrapper for nsfwimage and pull it out of the json

**Comment by samijandali** [comment]
hasn't this been resolved, NSFW images have an overlay of a red background and the slashed eye icon. So is this still needed? For NSFW and Spoilers?

**Comment by colejd** [comment]
Yeah, this is done.
