### ISSUE TITLE
Long posts not displayed fully

### ISSUE THREAD

**Issue by loskristianos** [ccrama/Slide-iOS#185]
Lengthy text posts are truncated when viewed in slide

E.g the following post cuts off at “Wrestlemania 30 - Daniel Bryan v Batista v Randy Orton” rather than displaying the full post

https://www.reddit.com/r/SquaredCircle/comments/85398x/an_indepth_look_at_every_4_star_rated_match_at/

**Comment by loskristianos** [comment]
iPhone X iOS 11.3b6 if that makes any difference. 

(Incidentally the same post correctly displays in full on Slide for Android).

**Comment by ccrama** [comment]
Fixed for Alpha 5!
