### ISSUE TITLE
Random crashes when viewing v.redd.it links

### ISSUE THREAD

**Issue by ChadShenk** [ccrama/Slide-iOS#187]
The app randomly crashes when viewing v.redd.it links. Doesn't seem to be related to any particular ones, and not all of them are affected. If a link is affected, it will first blank out the media viewer, then crash to the home screen a few seconds later.

**Comment by ccrama** [comment]
Do you have any example links (comments not to the video) for this? It is probably not random and if I can find a link between them that would be key to fixing the issue :)

**Comment by ChadShenk** [comment]
Here is an example link of one that crashes for me.

https://www.reddit.com/r/WTF/comments/8buytu/synchronized_stupidity/

**Comment by ccrama** [comment]
Should be fixed now!
