### ISSUE TITLE
App crashes when Airplane mode is cycled

### ISSUE THREAD

**Issue by ChadShenk** [ccrama/Slide-iOS#188]
The app crashes when Airplane mode is cycled. Would be great if it could gracefully stop trying to fetch data until it detects the device is back online.

**Comment by ccrama** [comment]
It is actually supposed to work totally offline with cached data, can you open the app at all when you are in airplane mode?

**Comment by ChadShenk** [comment]
The app opens when airplane mode is on, but if you turn airplane mode on while the app is already open it crashes.

**Comment by ccrama** [comment]
Should be fixed now
