### ISSUE TITLE
Top of the app is cut off 

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#198]
Slide v0.5.11, iPhone SE 10.2.1

Video of the issue:
https://streamable.com/gc86v

**Comment by ccrama** [comment]
Interesting, what device are you using? Cannot reproduce on iPad or iPhone 6s

**Comment by ccrama** [comment]
What happens if you enable the bottom bar in comments?

**Comment by incIined** [comment]
@ccrama no change.

**Comment by ccrama** [comment]
Also how are you doing video on iOS 10?

**Comment by incIined** [comment]
@ccrama yep, cut off on main page. 

I'm using the Cydia tweak "EasyRecord" by SparkDev.

**Comment by ccrama** [comment]
Ah gotcha, should be fixed now

**Comment by ccrama** [comment]
If it is not fixed in the update I'm pushing out momentarily, please re-open this!

**Comment by incIined** [comment]
Unfortunately, it is not fixed in 0.5.12.

https://streamable.com/egdk4

**Comment by ccrama** [comment]
I'm probably going to have to buy an iOS 10 device to test this on

**Comment by ccrama** [comment]
Fixed
