### ISSUE TITLE
Sliding down multiple times past the top of the page crashes the app

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#199]
Slide v0.5.11, iPhone SE 10.2.1

Sorry if the title doesn't make sense, don't know how else to put it. CrashReporter doesn't grab a crash log so I'm not sure how to post one here. 

Videos of the issue: 
https://streamable.com/c5rtm
https://streamable.com/jt2i6
https://streamable.com/an9po

**Comment by jglass071** [comment]
Happens too on iPad Pro 9.7 iOS 12 DB1 on Slide 1.0 Beta RC

**Comment by ccrama** [comment]
Fixed!
