### ISSUE TITLE
Syncing new content fails

### ISSUE THREAD

**Issue by ChadShenk** [ccrama/Slide-iOS#207]
When opening the app after the latest update, it tries to load for a few seconds and then goes straight to ‘showing offline content’. The only page that will load, is r/frontpage which shows the content from r/all instead of my subscribed subreddits.

**Comment by ccrama** [comment]
Reddit is actually down this morning, great timing haha. Give it a few hours and it should resolve itslef

**Comment by ChadShenk** [comment]
That’s an interesting coincidence. Happened as soon as I updated to the latest version of Slide on TestFlight. Good to know it’s not on Slide’s end, thanks.

**Comment by ccrama** [comment]
Wouldn't be the first time that it seems my app updates cause massive Reddit outages 😛
