### ISSUE TITLE
Ordering subreddits by A to Z affects Front Page & All as well

### ISSUE THREAD

**Issue by jglass071** [ccrama/Slide-iOS#208]
In Settings > Manage your subreddits, pressing the A-Z order button also affects r/frontpage and r/all, meaning the default sub when you open the app is whichever sub is ordered first not the frontpage.

Version: 1.0 Beta RC
iOS: 12 DB1
iPad Pro 9.7

**Comment by ccrama** [comment]
Good find, fixed!
