### ISSUE TITLE
During fingerprint authentication background is black

### ISSUE THREAD

**Issue by jglass071** [ccrama/Slide-iOS#209]
Inconsistent with main app theme that the user has chosen (in my case white). There is no animation between authenticating and opening the app with the lighter theme.

**Comment by ccrama** [comment]
That is on purpose, as it hides whatever was currently on your screen. Would you recommend making it the current theme background color?

**Comment by jglass071** [comment]
That's what I was thinking, yes. Makes sense to hide content, that is the point of the fingerprint lock.

**Comment by ccrama** [comment]
Done!
