### ISSUE TITLE
Pro purchase screen too far to right

### ISSUE THREAD

**Issue by jglass071** [ccrama/Slide-iOS#210]
![46ace008-1373-406b-82e5-1665c7d3ed9e](https://user-images.githubusercontent.com/18504622/41251039-a73034f0-6db0-11e8-9c13-82562aa98a4c.png)

Works fine in portrait orientation

iPad Pro 9.7 iOS 12

**Comment by ccrama** [comment]
Good find, fixed! Thanks!
