### ISSUE TITLE
Text misaligned/not wrapping 

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#211]
iPhone SE 10.2.1, Slide 1.0.0 (13)

Username:
![](https://i.imgur.com/MXkr369.jpg)

Wrapping:
![](https://i.imgur.com/uhBDM5f.jpg)

**Comment by incIined** [comment]
Slide 1.0.0 (14) 

![](https://i.imgur.com/VpgwVLv.jpg)

**Comment by ccrama** [comment]
I believe I have this all fixed now!

**Comment by incIined** [comment]
![](https://i.imgur.com/fGQfw0r.jpg)

![](https://i.imgur.com/AQCannH.jpg)

**Comment by incIined** [comment]
@ccrama sorry, could you be a little more clear? I'm kinda confused what you want me to do. Like, switch accounts then close and reopen the app? Or something else?

**Comment by incIined** [comment]
Yes, still cut off if I open the app, switch accounts, close the app, and then reopen the app and then the toolbar.

**Comment by ccrama** [comment]
This is in build 20 not 19 (same with your other replies, sorry should have been more clear!)

**Comment by incIined** [comment]
Ah ok. I'll wait for the new build to hit TF then 👌

**Comment by incIined** [comment]
Unfortunately, still happens on 20. 

![](https://i.imgur.com/pU0XZeF.jpg)

![](https://i.imgur.com/Gwgwasv.jpg)

![](https://i.imgur.com/wpPgfoT.jpg)
