### ISSUE TITLE
Unnecessary Alamofire

### ISSUE THREAD

**Issue by ReeceHumphreys** [ccrama/Slide-iOS#219]
Wanted to create an issue before working on the code. Is there any reason in particular for using Alamofire and SwiftJSON rather than the native URLSession provided by Foundation? Over the past few years, the API for URLSession has become much nicer to work with and it would help remove unnecessary dependencies from the project.

**Comment by nalexander50** [comment]
The Codable API is super nice. I like using it a lot more than SwiftyJSON which was previously my go-to. I agree it would help to reduce unnecessary dependencies.

**Comment by ccrama** [comment]
Alamofire is mainly used for multipart form uploads to imgur so Slide can support creation of albums, and is used in the video display code to get progress callbacks during download. Last time I checked the URLSession didn't support multipart, but I could be wrong? Any suggestions are welcome :)

**Comment by ccrama** [comment]
Thoughts @ReeceHumphreys @nalexander50 ?

**Comment by nalexander50** [comment]
Sorry, I intended to reply to this. I think Alamofire can definitely provide added value. I am not familiar with `URLSession` aside from very simple REST requests. I don't have much to offer there.

I do think there may be value added in switching to the `Codable` protocol over SwiftyJSON, though. From my time working with SwiftyJSON, I think that `Codable` is a much cleaner API and reads more nicely while also being very easy to use. Provided that the network layer is even moderately abstracted, it should be pretty easy to convert. Plus, you get the added benefit of never worrying about if SwiftyJSON gets updated or doesn't get updated.

**Comment by ReeceHumphreys** [comment]
I have done all of my network layers with URLSession and would highly recommend it. objc.io has some great videos on writing a clean, abstracted network layer with URLSession and Codable on Swift talk.

**Comment by colejd** [comment]
We'll be taking a look at this when we move to Swift 4.
