### ISSUE TITLE
Unsubscribing from managing Subscriptions

### ISSUE THREAD

**Issue by GIVEMEARUNFORMYMONEY** [ccrama/Slide-iOS#220]
Tried to remove and unsubscribe to different Subreddits from the 'Manage your Subreddits' on Settings, but after hitting 'Remove and Unsubscribe' it doesn't actually do anything.

**Comment by ccrama** [comment]
Interesting, does it work if you just do remove?

**Comment by GIVEMEARUNFORMYMONEY** [comment]
Yes, removing it only works.

**Comment by ccrama** [comment]
Were you signed in?

**Comment by ccrama** [comment]
Fixed
