### ISSUE TITLE
Tapping “saved submissions” whilst being logged out causes Slide to crash

### ISSUE THREAD

**Issue by reedhaffner** [ccrama/Slide-iOS#226]
However if you are logged in, Slide does not crash.

Perhaps a workaround for the bug would be a pop up that informs the user “You must be logged in to view saved submissions/posts!”.

Edit: Slide also does not have a pop up or way to handle users who post too often and thus crashes when a user taps on submit post.

The bug can be similarly resolved with a pop up that informs users “You are posting too often/you don’t have enough karma to post!”.

[From Reddit](https://www.reddit.com/r/slide_ios/comments/8sbq0l/bug_tapping_saved_submissions_whilst_being_logged/)

**Comment by ccrama** [comment]
Fixed the original issue! Also do you mind making the "Posting too often" alert a new issue? Thanks!
