### ISSUE TITLE
Post layout preview not displaying correctly

### ISSUE THREAD

**Issue by reedhaffner** [ccrama/Slide-iOS#227]
[Image](https://i.redditmedia.com/-1xwsUMwzeGvIh8bcMz1C8ImEBL7qZEjlopJCbuOG4E.jpg?fit=crop&crop=faces%2Centropy&arh=2&w=640&s=27aa1443be4af57dda68c6d92ea79e65)

[Reddit link](https://www.reddit.com/r/slide_ios/comments/8sbmks/bug_post_layout_preview_not_displaying_correctly/)

**Comment by ccrama** [comment]
Fixed!
