### ISSUE TITLE
Collapsing comments

### ISSUE THREAD

**Issue by GIVEMEARUNFORMYMONEY** [ccrama/Slide-iOS#232]
Occasionally instead of it actually collapsing, it just leaves a box empty the same size as the comment was. (Mostly the feature works fine but noticed it sometimes doesn't collapse properly)

**Comment by LittleGhostyBooBoo** [comment]
![Example image of this issue. by LittleGhostyBooBoo](https://i.imgur.com/mh07OxD.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ccrama** [comment]
Key detail is it's only when there are no children :D

**Comment by ccrama** [comment]
Fixed!
