### ISSUE TITLE
Comment action buttons not initially visible when expanded for the last comment

### ISSUE THREAD

**Issue by LittleGhostyBooBoo** [ccrama/Slide-iOS#235]
When I expand the comment action buttons for the final comment on a post, the comments shift up to make room for the action buttons, but then immediately shift down again to hide them.  I then have to scroll down to see the buttons. 

[Demo video](https://imgur.com/a/cTO4foa)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ccrama** [comment]
Fixed, there is padding below now!
