### ISSUE TITLE
Top menu gets cut off

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide-iOS#240]
https://imgur.com/a/vtvMc2d

**Comment by incIined** [comment]
Just happened to me. 

I added an account, went to add another account, got booted into Safari, exited Safari and went back into Slide, then clicked Guest.

**Comment by incIined** [comment]
Just happened to me again. Here's what I did:

Updated the app via TestFlight
Opened the app 
Switched to another account 
While the home screen was still loading in, I opened the menu

And the top bar was cut off. 

iPhone SE 10.2.1, Slide 1.1.2 (19)

**Comment by ccrama** [comment]
Agreed
