### ISSUE TITLE
Request: Add option to force landscape video in fullscreen

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#245]
Hello!

Could we have an option to force videos to be landscape-rotated (fullscreen) when opened, so that those of us who keep the rotation lock on don't have to fiddle with it a lot?

Thank you!

**Comment by ccrama** [comment]
Would this essentially open videos in landscape despite the current device orientation?

**Comment by colejd** [comment]
Yes, similar to how the YouTube iOS app opens videos in landscape when you hit the fullscreen button.

**Comment by ccrama** [comment]
Done with @colejd 's PR last week
