### ISSUE TITLE
Request: Add option for post view to show full image

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#247]
Hello!

Could we add an option to have the view of a post show the full-size image without clicking through? My rationale is this: If you're on the compact subreddit view and you click on an image post, you've already seen a thumbnail of the image, so the expectation is that what is displayed is the full image.

Here's an example:

<img src="https://user-images.githubusercontent.com/702432/41795596-4fc6495a-7631-11e8-9fa8-663d8bbd2cfa.png" width="50%"></img>

The image shown in the screenshot above is a small portion of the full image:

<img src="https://user-images.githubusercontent.com/702432/41795665-884a2904-7631-11e8-9bb4-6521ac313c22.png" width="50%"></img>

I think it would be better to show the full image from the outset to reduce the amount of clicking through that needs to be done to see the full image, since I see myself needing to do it for quite a few posts.

**Comment by ccrama** [comment]
Also, this is a setting on Android

**Comment by ccrama** [comment]
Done!
