### ISSUE TITLE
Overly difficult to download images on iPhone X

### ISSUE THREAD

**Issue by LittleGhostyBooBoo** [ccrama/Slide-iOS#251]
The download button is positioned next to the homebar at the very bottom of the screen making it quite difficult to actually tap. The homebar steals priority. 

The button should be moved vertically up so that the homebar has its own row. Furthermore, it would be nice to have a long-press or 3D Touch pop up in the image viewer to download images. 

![Example](https://i.imgur.com/6TdjvGn.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ccrama** [comment]
It is resized/with better padding now!
