### ISSUE TITLE
Username doesn't update when switching accounts 

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#253]
iPhone SE 10.2.1

Slide v1.1 (18)

In order to update it, I have to open the menu, click on my name to open the user profile, then go back to the main screen.

**Comment by ccrama** [comment]
Fixed!

**Comment by incIined** [comment]
Unfortunately, this is still an issue on Slide 1.1.2 (19).

**Comment by incIined** [comment]
Fixed in 20!
