### ISSUE TITLE
App crashing after posting a very long comment 

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#260]
iPhone SE 10.2.1

Slide v1.1 (18)

I typed out a 5 line comment with a lot of text, hit post, then the app showed me "sending" for a split second before crashing. Now, when I go to that comment thread, the app just crashes. 

https://streamable.com/tovzu

**Comment by incIined** [comment]
@ccrama https://reddit.com/r/androidroot/comments/8tr4fd/newbie/e19o0k3?context=3

The comment ended up posting successfully but it doesn't show up in my profile overview page.

**Comment by ccrama** [comment]
Probably fixed with my total comment rewrite, let me know if you experience it again!
