### ISSUE TITLE
`Unbalanced calls to begin/end appearance transitions`

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#266]
Found a weird one.

```
Slide for Reddit[11950:4934813] Unbalanced calls to begin/end appearance transitions for <Slide_for_Reddit.SingleSubredditViewController: 0x10503da00>
```

I found the source of the problem but I'm not sure what the solution is right now. On launch, the following happens in order:
1. `SingleSubredditViewController` calls `viewDidAppear`,
2. `MainViewController` calls `viewDidAppear`, 
3. `ColorMuxPagingViewController` calls `viewDidAppear`
4. `SingleSubredditViewController` calls `viewDidAppear` *again*

2 and 3 might be red herrings, but somewhere between 3 and 4 the message above is thrown. I think the issue is that `SingleSubredditViewController` is being presented twice.

Is step 1 necessary? As in, should `SingleSubredditViewController` be presented (or exist at all) before `MainViewController`?

**Comment by colejd** [comment]
Ignore this whole thing. The issue was caused by `viewWillAppear` being called in `MainViewController.doCurrentPage()` -- calling this manually will usually cause issues. I took it out and it doesn't appear to have had an impact on the program. I'll submit this fix as part of my next PR.

**Comment by ccrama** [comment]
Ah so interesting, thanks for finding that!
