### ISSUE TITLE
[Request] Adjust initial subreddit color selection

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#269]
Hi!

I'm not sure how the subreddit colors are chosen, but if they're random, could black and white be removed from the pool (possibly depending on the theme)? Several of my subreddits were set to black and they don't show up on the dark theme.

**Comment by ccrama** [comment]
They are actually chosen by the subreddits themselves, I believe I removed black from the pool already but white needs to be checked for still!

**Comment by colejd** [comment]
This is a more nuanced problem than I thought it would be. Working on it right now. We need to check to see if the color is too similar to the background color and exclude based on that, while supplying a color we know is going to contrast. For example, the text for /r/pics doesn't show up on the dark theme because it supplies the color `#222222`, while the background would be a similar dark color. We can't exclude specific colors because there would be so many, so we need a programmatic solution for this.

FWIW, I think we should just make the text for the subreddit in `CachedTitle` the accent color or something. That way we don't have to worry about this kind of unpredictability.

**Comment by ccrama** [comment]
I mentioned this on Discord, but the solution is already done on the Android app! Basically, we have already weeded out a list of colors to choose from which have proper contrast, all we need to do is match the HEX to the closest color in that list!

**Comment by colejd** [comment]
Fixed in latest commit.
