### ISSUE TITLE
Missing comments from profile overview 

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#270]
iPhone SE 10.2.1 
Slide 1.2 (20)

As the title states. A lot of comments are missing from the profile overview, and a refresh doesn't help. 

Slide:

![](https://i.imgur.com/XxAluCj.jpg)

Apollo: (warning - long screenshot so I'm not embedding it)

https://i.imgur.com/R7e4hgm.jpg

**Comment by incIined** [comment]
Ok, I just scrolled down and realized they weren't missing, it's just that the comment with 90 upvotes was in the wrong place.

**Comment by ccrama** [comment]
That's because Reddit has started fuzzing profiles and showing "suggested" parts of your profile unfortunately :/
