### ISSUE TITLE
Feature request - add currently logged in account in account switcher 

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#271]
As of Slide 1.2 (20), this is how it looks like if you have 3 accounts and are logged into one:

![](https://i.imgur.com/SygQ0Kw.jpg)

Would it be possible to have something like this, where it would display all your accounts with a (current) text next to the account you're currently logged into? Shitty mockup here:

![](https://i.imgur.com/x0SvBOj.jpg)

**Comment by ccrama** [comment]
Done, new menu will be in the next build!
