### ISSUE TITLE
Tapping on "Guest - tap to sign in" sends you to /u/guest instead of the Reddit sign in page 

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#272]
iPhone SE 10.2.1 
Slide 1.2 (20)

https://streamable.com/9rk6p

**Comment by ccrama** [comment]
Cannot repeoduce

**Comment by incIined** [comment]
How I reproduced:

Go into Slide
Log into an account
Close the app 
Reopen the app and you should be logged into an account 
Switch to Guest
Tap on the "tap to sign in"

**Comment by ccrama** [comment]
Yeah doing that just opens the account chooser for me. Strange.

**Comment by ccrama** [comment]
Either way, made that button open the switcher if it's guest and switched so it should work now either way
