### ISSUE TITLE
Feature request - add separator between comments in profile overview when using black base theme 

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#281]
iPhone 6S, 11.1.2
Slide 1.2 (20)

How it look right now:

![Image](https://i.imgur.com/oRDxYml.jpg)

Kind of hard to differentiate the separate comments. Would it be possible to add a thin white line either in between each separate comment, or maybe even add a white outline around each separate comment?

**Comment by incIined** [comment]
Or perhaps even making the title (of the post you’ve commented on) look different from the actual comment itself.

**Comment by ccrama** [comment]
Now there is an "AMOLED with Contrast" theme which does this!
