### ISSUE TITLE
Strike through formatting is missing

### ISSUE THREAD

**Issue by derek1906** [ccrama/Slide-iOS#282]
The following Markdown text means the text should be crossed out:

    ~~Foobar~~

but Slide displays the text with a big font size instead.

Here is a [gallery](https://imgur.com/a/Wybo5qY) showing the differences across different Reddit clients of the following Markdown:

    ~~Hello world~~

    #~~Title~~

Reference post: https://www.reddit.com/r/test/comments/8wgh55/strike_through_test/

**Comment by ccrama** [comment]
Was quite a hard one to track down and fix, but it's done for v22 coming out today!
