### ISSUE TITLE
Feature request - make subreddit/username clickable 

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#284]
iPhone 6S 11.1.2
Slide 1.3 (21)

![Image](https://i.imgur.com/QKCgJuv.jpg)

Instead of having to long press on the post title to bring up the menu to go to the subreddit or user page, we could go to the subreddit/user page directly from the post by clicking on that text.

**Comment by colejd** [comment]
We’re working on that one very soon :)

**Comment by derek1906** [comment]
+1

**Comment by colejd** [comment]
So uh, we didn't work on it very soon. But it's still on our radar! It will be done.

**Comment by colejd** [comment]
This is half done as of the latest build. Tapping on the subreddit name at the very top will now bring you to the subreddit in question.

**Comment by ccrama** [comment]
There were complications with this and I think it's more suited for a future update

**Comment by ccrama** [comment]
Pushing this to the next milestone so we might get to it by v6

**Comment by colejd** [comment]
Hey! Sorry it took so long, but it's finally done. When v2.0 comes out (soon), you'll be able to click on the username / subreddit on a post to go to their respective pages.
