### ISSUE TITLE
Feature request - view message you’re replying to while you’re typing it out

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#287]
Slide 1.3 (21)

Would love to have a feature where if you swipe down from the reply box, it’ll show the message you’re replying to, so you don’t have to keep going back to the PM overview to check what you’re replying to. 

Horrible mock-up here:

![](https://i.imgur.com/go8o5Ai.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ccrama** [comment]
I totally re-wrote that view, now it works like you requested and looks SO MUCH BETTER ;)
