### ISSUE TITLE
Bottom bar cutting off "download images" and "more options" button on bottom of image

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#297]
iPhone 6S 11.1.2

Slide 1.3 (22)

https://www.reddit.com/r/quityourbullshit/comments/8yj50g/whilst_trying_to_be_funny_make_sure_your/e2bghfc/

Happens on this comment. Buttons are unclickable while behind that bar. 

It's also blocked when you open the image normally (but after I loaded it once, it won't open again - opens with 3D touch though) might have something to do with how it's an album and not a direct image. 

https://streamable.com/7i5bw

**Comment by ccrama** [comment]
This view has been completely re-made for the next beta!

**Comment by ccrama** [comment]
Although the album loading looks to be a different issue

**Comment by ccrama** [comment]
Albums has been rewritten
