### ISSUE TITLE
Comment linked to wrong parent

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#299]
iPhone 6S 11.1.2

Slide 1.3 (22)

Link to comment:
https://www.reddit.com/r/Android/comments/8yk4t6/i_switched_from_a_pixel_to_a_mi_mix_2s_here_are/e2bmoga/

https://streamable.com/c43v8

Also didn’t show up in profile overview but I think that’s the issue with reddit “recommending” posts to show you (and I’m assuming that either can’t be fixed or it’s on the to-do list)

**Comment by ccrama** [comment]
The comment menu system/reply system is brand new in beta 24, so this will definitely be fixed. Also unfortunately no way to fix reddit's sorting :/

**Comment by incIined** [comment]
I see. How do other reddit apps show posts/comments chronologically though? Are they using their own method instead of Reddit’s or something?

**Comment by ccrama** [comment]
I think we're all affected, I've seen this on the apps I've tried and the
official app
