### ISSUE TITLE
Comments button spacing issue

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide-iOS#30]
The buttons look a little spaced out

**Comment by OrionDB5** [comment]
Comment buttons now are overlapping
![Screenshot](http://i.imgur.com/NY2BmwH.jpg)

**Comment by ccrama** [comment]
That has been fixed, I was actually referring to the VC toolbar

**Comment by OrionDB5** [comment]
Oops I read "comment buttons" instead of "comments button", it's just a slight difference but the meaning is completely different haha

**Comment by ccrama** [comment]
Should be fixed now!
