### ISSUE TITLE
Hide NSFW content in  Multitasking

### ISSUE THREAD

**Issue by AndroidKitKat** [ccrama/Slide-iOS#301]
Don’t know how possible this could be, but having the choice to hide the contents of the app if NSFW content might come in handy sometime. Here’s an idea how LastPass does this: https://usercontent.irccloud-cdn.com/file/bmnjFdbS/video.mp4
And I know other apps like banking apps and Signal Messenger frost the content view in the multitasking view.

**Comment by ccrama** [comment]
Slide does this if you have the biometric option turned on!
