### ISSUE TITLE
Refactor project to Swift 4

### ISSUE THREAD

**Issue by RJ-Clegg** [ccrama/Slide-iOS#305]
Hello!

We should update the project in the following ways: 

- [x] Add SwiftLint 
- [x] Migrate code from Swift 3 to Swift 4 
- [ ] Re work project structure to group by 'feature'  

As we go through the refactor this list will probably grow.

**Comment by ccrama** [comment]
We should also set up continuous integration 👍

**Comment by colejd** [comment]
We should also investigate moving away from Alamofire, since Swift 4's use of Codable makes interacting with JSON much easier. #219

**Comment by colejd** [comment]
We have a separate issue for the refactor and we just finished the Swift 4 conversion, so let's close this one.
