### ISSUE TITLE
Flair overlaps username when wrapping

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#311]
Slide 1.5 (27)

iPhone 6s 11.1.2

![](https://i.imgur.com/yI3Q4sI.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by colejd** [comment]
Should we put flair on a new line while we’re at it @ccrama?

**Comment by ccrama** [comment]
Honestly I think they belong with the username and should wrap, but looks like I need to make the baseline taller for the header of a comment

**Comment by ccrama** [comment]
Fixed!
