### ISSUE TITLE
Images very hard to dismiss

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#312]
Slide 1.5 (27)

iPhone 6s 11.1.2

When opening an image from the thumbnail while scrolling through a subreddit or from the actual post itself, you can’t dismiss it by swiping down. Instead, you have to swipe from the left in a specific way, and the animation to dismiss it will start to appear. But what you end up with is sliding in from the left while the image goes down, which is kind of confusing. 

https://streamable.com/u5qf7

Post:

https://reddit.com/r/jailbreak/comments/90lt0q/discussion_since_when_did_they_change_safe_mode/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ccrama** [comment]
@colejd 😅

**Comment by ccrama** [comment]
Was this fixed in build 28 @incIined ?

**Comment by ccrama** [comment]
Fixed *for* build 28!
