### ISSUE TITLE
Bottom bar icons not showing up

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#316]
Slide 1.5 (27)

iPhone 6s 11.1.2

Navigating from a post to a linked cross post, then to the sub the x-post is from will make the bottom bar unusable. It’ll appear, but there will be no icons. 

https://streamable.com/dzcl3

**Comment by incIined** [comment]
Never mind, found an easier way to reproduce. 

Go to a post from the front page> long press title > subreddit and then the bottom bar will blank out. 

https://streamable.com/k5j8z

**Comment by ccrama** [comment]
You have the bottom bar disabled in Settings > General, but also have sub tabs on, so it shows the sub tabs and the bottom bar on the main VC but not on the single subreddit

**Comment by colejd** [comment]
@ccrama this is happening for me with different settings. I don't have the bottom bar disabled, and I have sub tabs off.

**Comment by ccrama** [comment]
@colejd @incIined the icons are in the top bar, no? If that was the issue I have just fixed it, was an extra ! in an if statement :P

**Comment by colejd** [comment]
I'll see when it gets pushed, but for now I would definitely consider this
a bug. The icons are indeed in the top bar, but that preference hasn't been
set. Moreover the bottom bar isn't hiding when that button is moved.

**Comment by colejd** [comment]
(abusing my collaborator powers already. I'll close this again if that fixed it)

**Comment by ccrama** [comment]
Fix should be out!

**Comment by colejd** [comment]
I can’t repro this following the steps given, and it’s no longer happening for me in my scenario either.

**Comment by incIined** [comment]
>You have the bottom bar disabled in Settings > General, but also have sub tabs on, so it shows the sub tabs and the bottom bar on the main VC but not on the single subreddit

@ccrama ![GitHawk Upload by incIined](https://i.imgur.com/0GBF0wg.jpg)

These are my settings 

But I feel like the bottom bar should be disabled/hidden from the single subreddit view. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by incIined** [comment]
Still happening on 1.5 (33). Steps to reproduce are the same. 


https://streamable.com/jq317
