### ISSUE TITLE
Single-line code blocks in comments aren't sizing properly

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#319]
Title. The blocks don't seem to get enough height. I'll have a look at our comment sizing code -- since it's in a table view, we should be able to do automatic cell sizing without any of the elements in the cells compressing themselves.

**Comment by colejd** [comment]
This is also happening with some larger code blocks when the comment is fully collapsed and reopened.

**Comment by ccrama** [comment]
Do you have a link example?

**Comment by ccrama** [comment]
Fixed, but did not fix the close/re-open. The close/re-open issue is caused because the tableview estimates the cell height very incorrectly. You think that should be a separate issue?

**Comment by colejd** [comment]
It shouldn’t be doing that. It’s all AL for comments now, right? Perhaps you need to increase the compression resistance.

**Comment by colejd** [comment]
Fixed.
