### ISSUE TITLE
Breaking constraint for YouTube player view

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#325]
There are multiple constraints for height. One is set to 0, and the other is set to the proper aspect ratio height. I'm sure this is just setting two constraints instead of overwriting the one that already exists.

[Issue on WTF Auto Layout](https://www.wtfautolayout.com/?constraintlog=%22%3CNSLayoutConstraint%3A0x1c409b080%20YTPlayerView%3A0x107d3c3f0%2Eleading%20%3D%3D%20UILayoutGuide%3A0x1c41a3720%27UIViewSafeAreaLayoutGuide%27%2Eleading%20%20%20%28active%29%3E%22%2C%0A%20%20%20%20%22%3CNSLayoutConstraint%3A0x1c409b0d0%20YTPlayerView%3A0x107d3c3f0%2Etrailing%20%3D%3D%20UILayoutGuide%3A0x1c41a3720%27UIViewSafeAreaLayoutGuide%27%2Etrailing%20%20%20%28active%29%3E%22%2C%0A%20%20%20%20%22%3CNSLayoutConstraint%3A0x1c4099000%20YTPlayerView%3A0x107d3c3f0%2Eheight%20%3D%3D%200%2E5625%2AYTPlayerView%3A0x107d3c3f0%2Ewidth%20%20%20%28active%29%3E%22%2C%0A%20%20%20%20%22%3CNSLayoutConstraint%3A0x1d0693dd0%20H%3A%7C%2D%280%29%2D%5BUIView%3A0x109241c40%5D%20%20%20%28active%2C%20names%3A%20%27%7C%27%3AUIView%3A0x109241a50%20%29%3E%22%2C%0A%20%20%20%20%22%3CNSLayoutConstraint%3A0x1d0694000%20UIView%3A0x109241c40%2Etrailing%20%3D%3D%20UIView%3A0x109241a50%2Etrailing%20%20%20%28active%29%3E%22%2C%0A%20%20%20%20%22%3CNSLayoutConstraint%3A0x1cc09c980%20YTPlayerView%3A0x107d3c3f0%2Eheight%20%3D%3D%200%20%20%20%28active%29%3E%22%2C%0A%20%20%20%20%22%3CNSLayoutConstraint%3A0x1d0482b70%20%27UIView%2DEncapsulated%2DLayout%2DWidth%27%20UIView%3A0x109241a50%2Ewidth%20%3D%3D%20375%20%20%20%28active%29%3E%22%2C%0A%20%20%20%20%22%3CNSLayoutConstraint%3A0x1c409a0e0%20%27UIViewSafeAreaLayoutGuide%2Dleft%27%20H%3A%7C%2D%280%29%2D%5BUILayoutGuide%3A0x1c41a3720%27UIViewSafeAreaLayoutGuide%27%5D%28LTR%29%20%20%20%28active%2C%20names%3A%20%27%7C%27%3AUIView%3A0x109241c40%20%29%3E%22%2C%0A%20%20%20%20%22%3CNSLayoutConstraint%3A0x1c408e560%20%27UIViewSafeAreaLayoutGuide%2Dright%27%20H%3A%5BUILayoutGuide%3A0x1c41a3720%27UIViewSafeAreaLayoutGuide%27%5D%2D%280%29%2D%7C%28LTR%29%20%20%20%28active%2C%20names%3A%20%27%7C%27%3AUIView%3A0x109241c40%20%29%3E%22)

**Comment by ccrama** [comment]
Fixed 😎
