### ISSUE TITLE
Crash in inbox when swiping to "Unread" tab

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#327]

**Comment by ccrama** [comment]
Cannot reproduce, do you have no unread messages?

**Comment by colejd** [comment]
Correct.

**Comment by ccrama** [comment]
Not able to reproduce with an empty inbox, but I think I traced the crash to the WrappingFlowLayout. Will merge this with the feature request I make for that!

**Comment by ccrama** [comment]
Merge with #330

**Comment by colejd** [comment]
Here's an error message:
```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unexpected subviews'
```
