### ISSUE TITLE
Improve onboarding experience

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#328]
I think we need a better configuration experience at first launch. Some people I know who have tried the app have had trouble finding settings, wanted a different font, didn’t want the FAB, didn’t want the sliding tabs mode, and so on. So I’m advocating for making these things you pick yourself on first launch.

**Comment by colejd** [comment]
For things that greatly affect the experience, basically.

**Comment by ccrama** [comment]
- [ ] Make it run before MainViewController on first open
- [ ] Keep welcome screen with basic settings
- [ ] Option for sliding tabs mode
- [ ] Option for FAB
- [ ] Option for font 
- [ ] Option to log in? Maybe

**Comment by ccrama** [comment]
Done! Some of my goals changed throughout but I'm happy where it is right now
