### ISSUE TITLE
Implement new SelfSizingWaterfallCollectionViewLayout

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide-iOS#330]
https://github.com/adamwaite/SelfSizingWaterfallCollectionViewLayout

- [ ] Needs to be refactored to Swift
- [ ] Replace all WrappingFlowLayouts with this

Will be able to use AutoLayout (no more estimation code!!) and this is one of our biggest crash causes

**Comment by ccrama** [comment]
It also needs to respect the notch on the iPhone X (horizontal safe areas in landscape)

**Comment by colejd** [comment]
I'm going to postpone this for now in favor of other tasks. There's too much I don't understand at the moment about my test branch for this issue.

**Comment by ccrama** [comment]
😢

**Comment by colejd** [comment]
F

**Comment by colejd** [comment]
Just to elaborate why we tried this, gave up, and repeated three times: Auto Layout is not very happy with self-sizing cells that have text, and it's a lot slower doing that than precalculating the heights. We just need to live with it.
