### ISSUE TITLE
Sub name / search / sort bar cut off when opening post

### ISSUE THREAD

**Issue by sr0n** [ccrama/Slide-iOS#344]
Top bar is cut off when opening post. Scrolling down so it disappears then back up again fixes it. iPad Pro 9.7 12 DB6
![618dfc98-7137-4bac-824f-b007d08dddeb](https://user-images.githubusercontent.com/18504622/43783273-377ece16-9a59-11e8-8e5e-1ba27379ef81.jpeg)

**Comment by ccrama** [comment]
Fixed!
