### ISSUE TITLE
Media background blur inconsistency

### ISSUE THREAD

**Issue by jo-shih** [ccrama/Slide-iOS#365]
Right now the background blur for single images is different from other types of media. Example: [single image](https://imgur.com/rP7X1Db) vs [albums, videos, gifs](https://imgur.com/7mLzDoo)

Also, videos such as gifs initially appear against a completely black background, and becomes blurred once the content is moved slightly. Not sure if intentional. [Example](https://streamable.com/9jf3z)

iPhone X on 11.4.1
Slide v33

**Comment by colejd** [comment]
Both valid. We'll look into it.

- [ ] Find and fix alpha bg in video media VC
- [ ] Restore fullscreen state when the dismiss gesture takes the video out of fullscreen but doesn't complete

**Comment by ccrama** [comment]
That is actually the intended behavior @colejd , as for the differing states, just fixed it so images/albums are now identical, and videos are supposed to be black

**Comment by ccrama** [comment]
Done and done!
