### ISSUE TITLE
Striked out text misaligned 

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#368]
Slide 1.5 (33)

iPhone 6s 11.1.2

https://reddit.com/r/JailbreakSwap/comments/8xo3fy/usmd_h_iphone_6s_64gb_gold_on_ios_91_tmobile_only/

![Image](https://i.imgur.com/lUaBWNT.jpg)

**Comment by ccrama** [comment]
That is all in UIKit, don't know if it's possible to debug or fix this

**Comment by ccrama** [comment]
Fixed with the new text library!
