### ISSUE TITLE
Settings Improvements

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide-iOS#369]
- [x] Make accent color work instantly in Main theme
- [x] History settings, make 2 sections
- [x] Comments depth colors "space" hex is randomized (UIColor issue possibly @colejd ? Wasn't happening before the PR)
- [x] Select all in Subreddit themes
- [x] Color background of Subreddit themes and Manage subreddits
- [x] Subscribe when adding to Manage subs screen
- [x] Send message to Slide bot when user goes pro if they want to set their flair

**Comment by colejd** [comment]
That shouldn't be the case unless you're calling the weird code I wrote. Otherwise it's something else.

**Comment by ccrama** [comment]
We can leave the slide pro thing for later ;)
