### ISSUE TITLE
When viewing a gallery of images, the threshold between a horizontal swipe and a vertical/diagonal swipe is too small.

### ISSUE THREAD

**Issue by 2001ptrey** [ccrama/Slide-iOS#370]
It makes it extremely tough to look through galleries in the inline viewer.

**Comment by 2001ptrey** [comment]
iOS 12 Beta 5, IPhone X, and beta version 1.5 build 32

**Comment by colejd** [comment]
Okay, cool. We’ve fixed this bug since the latest beta, so please reopen this issue if it resurfaces after the next release!
