### ISSUE TITLE
Switch to new bottom sheet implementation

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide-iOS#373]
The current MDC sheet is great, but it lacks a lot of customizability that I am looking for (mainly, the ability to not make it expand to a full sheet). 

An alternative that looks like it could work is https://github.com/gametimesf/GTSheet!

**Comment by colejd** [comment]
We were looking for an alternative because the Material bottomsheet stuff didn't expose some stuff we needed. We've since made a fork that exposes that stuff. Feel free to reopen if we want to revisit this topic.
