### ISSUE TITLE
Long username overlaps moderator button

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#375]
Slide 1.5 (34)

iPhone 6s 11.1.2

![Image](https://i.imgur.com/k5ZyjQe.jpg)

**Comment by colejd** [comment]
We have two options here as I see it. We can truncate long usernames, or we can alter the design so the username gets its own line. @ccrama?

**Comment by ccrama** [comment]
We could also do .sizeThatFits()!

**Comment by ccrama** [comment]
Fixed!
