### ISSUE TITLE
Purchasing Pro from settings menu causes settings view to appear broken

### ISSUE THREAD

**Issue by russjr08** [ccrama/Slide-iOS#388]
Hi!

Not sure if I’ll be able to reliably duplicate this bug as it involves purchasing the pro upgrade, but I noticed today after installing the App Store version (congrats btw!) and opting to purchase pro, when I went back to the main settings page, it appeared “broken” so to speak. 

[Here’s what I saw](https://imgur.com/a/biujYs5)

Version 1.0.1 build 38, running on the latest iOS 12 Beta.

**Comment by ccrama** [comment]
I believe this is fixed in v1.0.3. If you see this again please re-open this issue!
