### ISSUE TITLE
[bug] Rotating the app causes it to crash.

### ISSUE THREAD

**Issue by jackorias** [ccrama/Slide-iOS#391]
Running iOS 12 PB 5 on my 2017 iPad, with the iOS theme and list view on Slide.

Rotating the screen causes the app to crash, no matter where I am in the app. Please see a gif of it below. 

https://gfycat.com/RequiredSafeFinnishspitz

**Comment by colejd** [comment]
I’m experiencing this occasionally, and I’m pretty sure it’s a problem with iOS 12. We’ll look into it though.

**Comment by ccrama** [comment]
Fixed!

**Comment by ccrama** [comment]
I was forcing the tabbar to align to the top of a view it was not inside of if you had sub tabs disabled
