### ISSUE TITLE
Overhaul onboarding process

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#392]
I've noticed that a lot of our users were confused by the onboarding process. Some suggestions for improvement:

- [x] One setting per page. Users don't know what the toggles on the last page do and would benefit from a visual demonstration. Particularly for the FAB and swiping tabs mode.
- [ ] Add a toggle for choosing flat mode (more "iOS") and the regular mode (more "Android") to the initial onboarding experience. Perhaps instead of calling it flat mode, we make it a setting called "look and feel" or something where the user picks between "iOS" and "Material". This would allay some complaints about the app looking "too much like Android" (@ccrama if you're into this we should make a separate issue for this).
- [x] Rename the "iOS" theme to something more like "Light". This is confusing terminology and has caused some anger among people who thought it would have more effect on the UI than just affecting color.
- [ ] Add a guided onboarding experience to the Single Sub VC. Just something to say "the bottom left button is for navigation and settings, and the bottom right button is for subreddit-specific settings". 
- [ ] Provide guided onboarding for the video VC. Just something to say "long press to force rotate, double tap to seek".

**Comment by ccrama** [comment]
Closing, merging with #629
