### ISSUE TITLE
Browsing through large albums causes crash

### ISSUE THREAD

**Issue by djjcast** [ccrama/Slide-iOS#402]
The issue was noticed on an iPhone 6 Plus - 10.3.3 (14G60). Browsing through the following album causes a crash with no error message in Xcode's console.

https://old.reddit.com/r/DIY/comments/96c6yc/we_dont_have_any_trees_but_i_wanted_to_build_a/

The following changes resolve the issue for the above album:

https://github.com/djjcast/Slide-iOS/commit/4838113fe8ab7bc0d5995cae9e62bf2c2d4f4a4e

Although, the following, much larger, album still causes a crash with no error message:

https://old.reddit.com/r/MechanicalKeyboards/comments/8vkbzd/june_2018_utah_meetup_higher_quality_pics_in/

The following changes seem to improve performance but browsing the above album still eventually causes a crash:

https://github.com/djjcast/Slide-iOS/commit/eba8d5a52b103be9e00ddb4eb460db64c7902934

Maybe there's a memory leak somewhere? Browsing through albums causes the memory usage to continually increase - see https://stackoverflow.com/a/31819410 (not sure if it's true or still relevant). Maybe UIPageViewController isn't suited to be used as an image browser?

Maybe the Gallery view can be repurposed as an album viewer since it seemed to perform well?

**Comment by colejd** [comment]
Thank you for the thorough report!

I think we've isolated at least one potential source of the bug: https://github.com/ccrama/Slide-iOS/blob/1347e3e0ba7b999889f832e54d09bac093139f26/Slide%20for%20Reddit/PostContentPresentationManager.swift#L12

This should be weakly held since the class around it is lazily instantiated.

Either way, I'll do an audit for leaks.

**Comment by djjcast** [comment]
Thanks @colejd, making that variable `weak` seems to have improved performance a bit but the app still crashes while browsing the second, larger album. Please let me know if there are any other changes you would like for me to test.

**Comment by ccrama** [comment]
@djjcast your changes appear to be working, so I will include them soon. As for that memory leak, is that still an issue @colejd ?

**Comment by ccrama** [comment]
Scrolling through albums now does *not* continuously increase my ram

**Comment by djjcast** [comment]
Here's another potential source or the memory leak: https://xebia.com/blog/function-references-in-swift-and-retain-cycles/

Although, I'm still seeing the memory usage continually increase after changing

https://github.com/ccrama/Slide-iOS/blob/c1091e434e26282dee006c1f19d14406bada7285/Slide%20for%20Reddit/ModalMediaViewController.swift#L57-L58

to

        embeddedVC.commentCallback = { [weak self] in
            self!.commentCallback!()
        }
        embeddedVC.failureCallback = { [weak self] (url) in
            self!.failureCallback!(url)
        }

**Comment by ccrama** [comment]
I am not convinced it is a memory leak, I have been doing profiling for leaks and Instruments is not finding AlbumVC related leaks. I think this is just a case of too much RAM usage

**Comment by ccrama** [comment]
@djjcast any improvements with 21e2adc3ef478745d4bec742c5f3abdf7f971472?

**Comment by djjcast** [comment]
I agree, I couldn't find any signs of leaks using the Leaks instrument or this method: https://medium.com/zendesk-engineering/ios-identifying-memory-leaks-using-the-xcode-memory-graph-debugger-e84f097b9d15

Unfortunately, the app crashed while browsing the second album with the latest version.

Also, the bottom-left menu is just showing the keyboard when pressed: https://i.imgur.com/RtKnDln.jpg

**Comment by colejd** [comment]
Hearing there are no obvious leaks makes me really happy and slightly upset at the same time.

Also we're working on the menu. I'll have a fix out within a few hours.

**Comment by ccrama** [comment]
@djjcast are you sure that it is a memory crash, and not a crash trying to load a specific image *in* the album?

**Comment by djjcast** [comment]
I don't think it's any one particular image since the crash happens at different points within the album. Although, some images in the album are much larger than others - like [image 13 (1000x750)](https://i.imgur.com/B5fiD9P.jpg) vs [image 14 (5753x3835)](https://i.imgur.com/3UUZHJW.jpg). There is noticeable lag when switching to one of the larger images in the album.

The latest version of SDWebImage has an option called SDWebImageScaleDownLargeImages that sounds like it might help: http://cocoadocs.org/docsets/SDWebImage/4.1.2/Constants/SDWebImageOptions.html

**Comment by colejd** [comment]
That’s great. Should cut down on RAM usage quite a bit. @ccrama let’s do this next?

**Comment by ccrama** [comment]
I have added that in @djjcast ! Although I doubt it will solve this completely, does it help?

**Comment by djjcast** [comment]
Yes, it seems to have helped but the app still crashes before I reach the end of the [second album](https://old.reddit.com/r/MechanicalKeyboards/comments/8vkbzd/june_2018_utah_meetup_higher_quality_pics_in/).

Fortunately, I found that adding `SDImageCache.shared().config.shouldCacheImagesInMemory = false` after https://github.com/ccrama/Slide-iOS/blob/72d6de7324f6afd7285aa6cece6d049bc26b5412/Slide%20for%20Reddit/AppDelegate.swift#L141 lets me browse to the end of the album without crashing. This pretty much confirms that the issue is excessive RAM usage.

I noticed the [`maxMemoryCost` and `maxMemoryCountLimit`](https://github.com/rs/SDWebImage/blob/9de56b013aca7bcfae68d78b2fd9db13e6becb45/SDWebImage/SDImageCache.h#L64-L72) can be set to tune how the memory cache works. Although, do you think caching images in memory should just be completely disabled - at least for devices with less than a certain amount of RAM? Besides occasionally scrolling back and forth through an album or up and down a subreddit listing, I rarely see the same image more than once when browsing reddit with Slide - it would be a waste if far more images are ever added to the memory cache than ever retrieved.

Also, [`self.updateProgress(CGFloat(average), "")`](https://github.com/ccrama/Slide-iOS/blob/master/Slide%20for%20Reddit/ImageMediaViewController.swift#L216-L226) should happen in the main thread to see the progress indicator update:

    DispatchQueue.main.async {
        if average > 0 {
            self.size.text = fileSize
            if total == 0 {
                self.parent?.dismiss(animated: true, completion: {
                    self.failureCallback?(imageURL)
                })
            }
        }
        self.updateProgress(CGFloat(average), "")
    }

and the image count text color ("1/280") is now black instead of white: https://i.imgur.com/ieIsHrs.jpg

**Comment by djjcast** [comment]
Also, I remember reading online somewhere that if an app is going to crash due to excessive memory usage, [`didReceiveMemoryWarning`](https://github.com/ccrama/Slide-iOS/blob/72d6de7324f6afd7285aa6cece6d049bc26b5412/Slide%20for%20Reddit/AlbumViewController.swift#L252-L255) is never called or if it is called, it's at a point in which it's too late to recover from the pending crash - which is why clearing the memory in `didReceiveMemoryWarning` isn't preventing the crash.

**Comment by ccrama** [comment]
I think the solution would be disabling in-memory while in media views (shadowbox, albums, etc), and enabling it on viewWillDisappear. Should be pretty easy to put it into the god class for all medias!

**Comment by ccrama** [comment]
Done! Feel free to re-open this if the issue persists after my changes @djjcast
