### ISSUE TITLE
Text over text after folding/revealing comment

### ISSUE THREAD

**Issue by david-me** [ccrama/Slide-iOS#411]
I was only able to reproduce this in one place, on a specific comment, but after tapping and hiding the comment, then tapping again to reveal it, the comment’s text appears to be overlaying the child comment’s text

iOS 11.4.1, iPhone 6s+, build 1.0.3

[Screencast](https://nextcloud.apps.davidm.me/index.php/s/RpmayAfRLBZZ38b)

And [link to the post](https://reddit.com/r/vim/comments/97v0ix/how_do_people_use_vim_which_does_not_have_ide/) featured in the screencast

**Comment by ccrama** [comment]
Is this reproducible every time?

**Comment by david-me** [comment]
Yes, every time I fold and unfold the comment the same thing happens (even after quitting the app)

**Comment by ccrama** [comment]
Fixed now!
