### ISSUE TITLE
Onboarding bug on small-sized iPhones (5s/SE)

### ISSUE THREAD

**Issue by mmshivesh** [ccrama/Slide-iOS#412]
![img_3568](https://user-images.githubusercontent.com/23611514/44296046-9c5deb00-a2d3-11e8-9c10-54daa4c93d72.PNG)

The paging indicator overlaps on the theme selector

**Comment by ccrama** [comment]
What app version are you on? I cannot reproduce this after v1.0.2

**Comment by mmshivesh** [comment]
Whoops. I was on the pre-release `v1.5 Build 22`. Updating to the AppStore version `v1.0.3` seems to have fixed it. 
![img_3594](https://user-images.githubusercontent.com/23611514/44299527-88d37400-a315-11e8-8b30-0a4f99fb84dd.PNG)
