### ISSUE TITLE
Monochrome depth colors include purple

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#414]
![6d933410-94ce-4d67-99ef-c8175f59e8c5](https://user-images.githubusercontent.com/26832587/44301516-99fc9080-a2d5-11e8-877c-15a2ed63f2a9.png)

**Comment by ccrama** [comment]
That is the op of the comment chain ;)

**Comment by WickedColdfront** [comment]
Aha! That makes sense, thanks!
