### ISSUE TITLE
Multiple Fab Buttons After Rotation

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#417]
I can reproduce this pretty regularly by doing the following:
-swipe to change subreddit
-rotate device from portrait to landscape
-swipe to change subreddit
-rotate device from landscape to portrait
-repeat (usually takes 2 or 3 times)

I’m on iOS 11 using an iPad Mini 4. 

![04005c0e-23d9-4361-87cc-987045329e75](https://user-images.githubusercontent.com/26832587/44302291-cc60ba80-a2e2-11e8-8214-6c0fcf6588d8.jpeg)

**Comment by ccrama** [comment]
Should be fixed now
