### ISSUE TITLE
Rethink UI placement for nav and user actions

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#425]
Introduced the new discussion tag to denote that this isn't a request so much as something I wanted to talk about.

I think there are some things in the current UI that could be moved around to make things more user-friendly. For example, user stuff should probably be taken out of the nav menu so that it can be presented in more places. As it stands, to switch accounts or check your inbox, you have to go all the way back to the root SingleSubredditVC and open the nav menu from there. Users should be able to access that from any instance of SingleSubredditVC.

If we do that and remove the settings button from the nav menu, then the nav menu is no longer really a multi-purpose menu so much as a quick switcher for subs. And in that case I think we could make that trigger by clicking either a magnifying glass button or the subreddit name itself.

Here's a rough mockup of what I'm talking about.

<img src="https://user-images.githubusercontent.com/702432/44409388-4afe6780-a530-11e8-8c55-2cccce65968d.png" style="max-width:100%;" width="50%"></img>

We could then move the subreddit "more" button up to the top bar, making the whole thing subreddit-centric.

The only issue is where to keep the settings and account buttons. We could keep them in the bottom bar, or put them in a radial menu like so (another bad mockup incoming):

<img src="https://user-images.githubusercontent.com/702432/44409815-17700d00-a531-11e8-9bd0-1c7b0c8ac0f4.png" style="max-width:100%;" width="50%"></img>

I think all this would go a huge amount toward improving the UX. Take or leave any amount of this -- just wanted to get a discussion going.

**Comment by ccrama** [comment]
I think what would be useful is allowing the user to set any of the actions they want in the app. So they can set the fab button, either side button, and top buttons to their liking. It would also allow iPads to show more buttons than just one on the iPhone
