### ISSUE TITLE
App crashes when quickly double-tapping some comments

### ISSUE THREAD

**Issue by OrionDB5** [ccrama/Slide-iOS#43]
Just noticed this, I think it may be related to the number of comments as doing the same on a comment with 32 replies doesn't crashes the app.
One of the comments that crashes the app (63 replies at the moment): https://www.reddit.com/r/pics/comments/6nptzo/kid_was_desperately_trying_and_failing_to_do_it/dkbbdx2/

iPhone 7, iOS 10.3.2

EDIT: added device and iOS version

**Comment by ccrama** [comment]
I just did a ton of additions to the comment VC, did that fix your issue?

**Comment by OrionDB5** [comment]
I already pulled your latest commit and compiled from that. I'm not completely sure but I don't think it happened before (I also tried the previous commit for some hours about 4-5 days ago)

**Comment by ccrama** [comment]
Should be fixed now
