### ISSUE TITLE
Play sound on videos when silent mode is enabled

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#433]
I’m not sure if this would be the expected behavior for everyone, so it should probably be a setting that can be disabled. 

I think that “silent mode” is meant to mute alerts from calls and text messages; not mute sounds from media. 

There is no audio on videos when silent mode is enabled.  The expected behavior would be to play audio - similar to videos in the YouTube app and embedded videos in Safari.

**Comment by colejd** [comment]
There is a bit of a discussion to be had about this, I think. Some apps do what we do, and others don't. Regardless of intent, I find it useful that I have a guarantee that a random .mp4 on Imgur isn't going to play audio in a situation where I don't want it. 

My personal feelings aside, from a code standpoint we set the audio session to the `AVAudioSession.Category.ambient` category. In the [docs](https://developer.apple.com/documentation/avfoundation/avaudiosession/category/1616560-ambient), this is for apps that "can be used successfully with the audio off", and that's really all that it specifies for usage intent. This is effectively equivalent to using the `playback` category and turning on the `mixWithOthers` option. I think we could switch to this and make that option, well, optional. @ccrama?

**Comment by ccrama** [comment]
There's a setting for it now in Settings > General!
