### ISSUE TITLE
Add warning before navigating away from a comment in progress

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#434]
With the in-line comment replies, it’s really really easy to accidentally close the comment and lose your progress. 

For example, while typing a reply a user might long click into the text box to copy/paste text or accidentally click the parent comment. Both of these scenarios currently collapse and discard the comment in progress. 

It would be nice if there was a warning prior to closing the comment and/or users had an opportunity to save the draft.

**Comment by ccrama** [comment]
Done!
