### ISSUE TITLE
SloppySwiper transitions are way too sensitive

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#440]
As it stands, any amount of swiping back will cause an implementing VC to close immediately. This is new behavior as of 1.1.0.

**Comment by colejd** [comment]
It seems to only happen if you have left side comment gestures turned on.

**Comment by ccrama** [comment]
hm sloppy swiper is *disabled* if you have that setting on

**Comment by ccrama** [comment]
I have disabled it in the sub vc for now

**Comment by colejd** [comment]
This has been fixed.
