### ISSUE TITLE
Some issues with the video player

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#443]
Slide 1.1 (45)

6s 11.1.2

Just tried playing this video: 

https://reddit.com/r/PublicFreakout/comments/99pqdj/woman_late_for_work_complains_loudly_on_bus_chill/

Some issues I noticed: 

1) when loading the video for the first time, when it finished loading, it got stuck on a blank screen. When I swiped the video stuck on the blank screen away, it started playing the video in the background even while I was in other posts. Couldn’t bring back the video back up to stop the audio, as reopening the video would just add another instance of the video so you would get audio doubled twice. Nothing appeared in the CC, and I was only able to stop it by opening the YouTube app, which caused Slide to pause the audio.

2) the video progress slider doesn’t go all the way to the left when at 0:00. 

3) skipping forward stops the video until you click “pause” and “play”  

4) when the above is happening, when clicking on the pause/play button, the animation from pause to play and vice verse sometimes doesn’t happen (or maybe the animation is just very slow? Idk)

5) happened once (right after the background playback issue) but when skipping forward, clicking pause then play would bounce me back to the beginning of the video, while the progress slider was still stuck where I clicked pause/play. 

Issues 2 to 4 can be found here: 

https://streamable.com/mrtz8

Also, a request: would it be possible to make the video player feel more native to iOS?

**Comment by colejd** [comment]
The video player really does need work. I’m looking at implementing streaming very soon so I’ll resolve as much of this as I can. 

As for making it feel more native, I need to also make sure it fits in with the rest of the app, know what I mean? Are there any features that you’re missing in particular? I plan on adding an indicator to tell you the current time of the video when you scrub.

**Comment by incIined** [comment]
>The video player really does need work. I’m looking at implementing streaming very soon so I’ll resolve as much of this as I can.  ...

@colejd personally, I think the video slider is too big. It also feels too high up and blocks the video a bit too much for my liking. And the design language doesn’t really fit into iOS, but idk if that’s intended or what. 

![](https://i.imgur.com/8Cp0SEz.jpg)

![](https://i.imgur.com/ZCFNxFk.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ccrama** [comment]
It looks almost identical to the collapsed version of the iOS media player, other than where it's positioned what does not look iOS about it? It's all stock components, same pause button, same time indicator, using a stock UISlider. It's high up so it doesn't interfere with the buttons below it in your screenshot

**Comment by colejd** [comment]
We've made some major improvements to the video player for v1.4. Let's close this and open a new ticket for further discussion if necessary so that it's in the context of the new update.
