### ISSUE TITLE
Investigate removing fade animation for cells with cached content

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#445]
Title. If a LinkCellView is loading cached content, I think it's fast enough that we can dispense with any fading animations. [Discussion here](https://old.reddit.com/r/slide_ios/comments/99r516/bug_browsing_and_scrolling_mediarich_subreddits/e4ql3mx/).

**Comment by ccrama** [comment]
We already do this:

`                        if cache == .none {
                            UIView.animate(withDuration: 0.3, animations: {
                                self.bannerImage.alpha = 1
                            })
                        } else {
                            self.bannerImage.alpha = 1
                        }
                    })
`

**Comment by ccrama** [comment]
That means the user is out of RAM and/or system storage space

**Comment by colejd** [comment]
That's what I thought. Closing!
