### ISSUE TITLE
Idea: Add Slide as a Share Target in Safari

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#447]
I’m not sure if this is possible, but....

Sometimes I’ll Google something and come across a post on Reddit that opens in Safari. It would be nice if I could easily open that post or subreddit in Slide.  Maybe hitting share in Safari would pass the link to Slide which could either open the content (if it’s a Reddit link) or start a new post (for all other links). 

If there’s already a way to do this, let me know!

**Comment by ccrama** [comment]
Merging with #140 ! Something that I definitely want to implement soon
