### ISSUE TITLE
Link to content is sometimes truncated

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#448]
When clicking the link from [this post](
https://reddit.com/r/dataisbeautiful/comments/9a74im/simple_idea_for_visualizing_temperature_trends/), I get the following error message, “Safari cannot open the page because the server cannot be found.”

URL passed to Safari:
http://blog/

Correct URL:
http://blog.cityprojections.com/2018/08/is-your-city-getting-hotter.html

**Comment by ccrama** [comment]
Fixed!
