### ISSUE TITLE
Post “tags” wrapped to the next line don’t have the appropriate amount of padding

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#449]
I feel like an asshole for posting this because it’s such a small issue, but it’s the little things, right??

The NSFW tag on the left should have rounded corners on all sides and should have some padding on the top so it isn’t so close to the line above.  The spoiler and bug tags on the right seem to be slightly cut off on the bottom. 

![8a517377-c01a-4954-9182-d12ec5aabfa1](https://user-images.githubusercontent.com/26832587/44634064-5cd97380-a951-11e8-8e5b-bddf6b6d71cc.jpeg)

**Comment by colejd** [comment]
These are just the kinds of things we want to know about.

**Comment by ccrama** [comment]
Not an issue with the new text lib
