### ISSUE TITLE
Comments font and highlight issue

### ISSUE THREAD

**Issue by djjcast** [ccrama/Slide-iOS#453]
With the comment font set to "Roboto Condensed" and size "Smallest", the score/time and "Load x more" text seems to be the wrong size: http://oi68.tinypic.com/x0rzwm.jpg

Also, when loading more comments, the "Highlight op replies of parent comments" feature isn't applied to highlight "op replies" purple:

before load more: http://oi63.tinypic.com/of4hz7.jpg
after load more: http://oi67.tinypic.com/2upxqfo.jpg

from: https://old.reddit.com/r/EarthPorn/comments/93tmex/always_looking_for_natural_frames_when_im_out/

**Comment by ccrama** [comment]
Both have been fixed! Thanks for the report

**Comment by djjcast** [comment]
Okay, thanks for the update. The changes fixed the issue on my device.

I'm not sure if it was intentional, but I noticed the height of the bottom toolbar increased after upgrading from version 1.1 to 1.2:

1.1: https://i.imgur.com/qwLXXAp.jpg
1.2: https://i.imgur.com/YCUMPsV.jpg

**Comment by ccrama** [comment]
It was intentional to add more room to drag from!

**Comment by djjcast** [comment]
Oh, okay, that makes sense. I guess something seemed off after being used to the shorter toolbar since the toolbar buttons are a little vertically off-center now.
