### ISSUE TITLE
Freezing when trying to open 3D Touch a reddit video

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#455]
Slide 1.2 (47)

iPhone 6s 11.1.2

https://reddit.com/r/gifs/comments/9bwq77/they_finally_did_it/

https://streamable.com/f7lsf

When you first open the video via 3D Touch, it’ll freeze the app. When you load the video then try to 3D Touch it, it’ll open up an error.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ccrama** [comment]
I think I have fixed this with the recent changes in v3.0, if not please re-open the issue!
