### ISSUE TITLE
Touch up video player UI

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide-iOS#466]
Edit per our discord chat

- [x] Move buttons to top
- [x]  Put background behind buttons
- [x] Move time elapsed indicator into scrubber
- [x] Put play/pause button in screen center
- [x] Animate the size of the scrubber thumb when scrubbing (default to small)
- [x] Make the scrubber track a bit thinner
- [x] Minimized volume bar

**Comment by ccrama** [comment]
@colejd

**Comment by colejd** [comment]
I'm going to redesign the progress bar to more or less match how it looks in the Music app. Not colorwise though. I'm going to make the bar thinner and the thumb very small, but it'll animate to be larger when the user interacts with it. I'll also be relocating the time remaining label and making a time elapsed label to match it.

**Comment by colejd** [comment]
@ccrama We should add a minimized volume bar too! https://github.com/andreamazz/SubtleVolume

**Comment by ccrama** [comment]
I am not convinced of item 1 or 2 anymore, I think the new implementation is pretty much done (except possibly making it closer to the bottom especially on rotation)

**Comment by ccrama** [comment]
Done and done!
