### ISSUE TITLE
Comment jumping causes navigation bars to stop autohiding

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#472]
https://www.reddit.com/r/slide_ios/comments/9e4ooj/bug_comment_jump/

**Comment by ccrama** [comment]
That is on purpose (it shouldn't autohide while jumping). Are you guys seeing different behavior?

**Comment by colejd** [comment]
Nope, just copying from Reddit. I do think that the autohiding behavior should restart when the user scrolls though.

**Comment by colejd** [comment]
Actually wait, I get why this is happening -- you're keeping it alive so that automated scrolling doesn't cause the bar to hide. How about putting a completion handler on that automated scroll and re-enabling the autohiding?

**Comment by ccrama** [comment]
Fixed!
