### ISSUE TITLE
Hitboxes off in settings.

### ISSUE THREAD

**Issue by mochajones10** [ccrama/Slide-iOS#481]
This is especially true when changing the default sorting for subreddits and comments. I'm not able to change my default comment sort and, to change default subreddit, i have to click the previous clickable option. using iPhone 8 Plus.

**Comment by ccrama** [comment]
That is actually because the setting is checking section 2 rows 1 and 2 for those, but it's actually section 3 that contains those settings. Has been fixed!

**Comment by mochajones10** [comment]
I tried to do this again, and still to no avail.

**Comment by ccrama** [comment]
There hasn't been an update for this yet

**Comment by colejd** [comment]
Just to be clear, are you on the latest App Store version, or are you building directly from the source? The App Store version hasn’t been updated yet.

**Comment by mochajones10** [comment]
Still on the latest store version. Not use to builder in iOS yet.
