### ISSUE TITLE
Drawer header color not set on device rotation

### ISSUE THREAD

**Issue by djjcast** [ccrama/Slide-iOS#484]
After rotating from portrait to landscape and back the drawer header looks like this: https://i.imgur.com/rNbgDcq.png. It looked like this before rotation: https://i.imgur.com/2aoFpuA.png.

**Comment by ccrama** [comment]
If you collapse and open it again in that state, does it become colored?

**Comment by djjcast** [comment]
No, it remains uncolored after collapsing and reopening. Selecting a subreddit from the drawer list or reselecting the base theme resets the drawer header color: https://i.imgur.com/XkLXTrS.mp4

**Comment by ccrama** [comment]
I think it's breaking the constraint, and opening a new sub resets the constraints! I think the color is fine but will look into it

**Comment by djjcast** [comment]
This issue is no longer present as of the latest version (commit 141be24d10d147b9123b0015d9950af90b595db2). The last version I had installed was d0624b88fc1fc25d6560206a7751298cd6ce371b so the issue must have been fixed some time between those two commit points.
