### ISSUE TITLE
Tapping to fullscreen a video that hasn't loaded yet will crash Slide

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#486]

**Comment by ccrama** [comment]
Are you building off of the Github source @Thlayli ?

**Comment by Thlayli** [comment]
@ccrama I'm just running the App Store version.

**Comment by ccrama** [comment]
@thlayli this doesn’t actually affect you then, inline videos are not out in the App Store yet

**Comment by ccrama** [comment]
Fixed @colejd

**Comment by Thlayli** [comment]
Oh, sorry. Is there an open bug report for sudden app crashes in the
release version?
