### ISSUE TITLE
Inline video audio continues to play after the video is no longer visible

### ISSUE THREAD

**Issue by djjcast** [ccrama/Slide-iOS#489]
See (has audio) https://streamable.com/ur696 - the audio stops after leaving the comments view.

Also, after returning from the comments view, the red audio icon is not visible when replaying the video: https://i.imgur.com/Lv7BASa.mp4 The audio plays when you click the video to show it fullscreen but remains muted when you dismiss the fullscreen view: (has audio) https://streamable.com/ow86h

I think it would be helpful to have an option to have inline videos play with audio unmuted. Sometimes I'll play a video inline and not realize it had audio until the end of the video. Or maybe there could be a quick animation that alerts the user that the inline video has audio? Maybe an animation like a larger version or the red audio icon starting in the middle of the video view and shrinking to the corner.

**Comment by ccrama** [comment]
Hmm, I am not able to reproduce this. I think what _might_ be happening in your case is the video is playing in the CommentVC which is actually still stored in memory (the last page is stored so you can return if you closed accidentally), but I do destroy the AVPlayer in the viewWillDisappear block. The LinkCellView there is actually completely recreated when returning to the subredditVC so you should not be seeing different behavior when returning (as it's essentially restarting the cell). It's possible that stored AVPlayer in the comment vc is taking the audio focus?

**Comment by djjcast** [comment]
That's weird, maybe the issue is iOS dependent? I notice this issue on an iPhone 6 Plus running iOS 10.3.3 (14G60).

Clean install: https://streamable.com/60ogy
\* Note that you can hear the audio doubled after the unmute button is pressed in the comments view.
Clean install with "Play videos on tap" set: https://streamable.com/6ew2x

**Comment by ccrama** [comment]
If the sound is doubled, that means there are two AVPlayer instances running at one time. It must be the one in comments not getting killed somehow 🤔

**Comment by ccrama** [comment]
Actually, I think pausing/muting the video when opening comments from the LinkCellView would fix this issue

**Comment by ccrama** [comment]
I think I fixed it in my latest commit, if not please re-open this!

**Comment by djjcast** [comment]
Okay, I just install the latest version and the main audio issue is fixed. There are still some cases where the unmute button isn't present. I'll see if I reproduce the issue.
