### ISSUE TITLE
Inline video progress indicator and time not visible on light background

### ISSUE THREAD

**Issue by djjcast** [ccrama/Slide-iOS#491]
See https://i.imgur.com/GNWaNuV.mp4.

**Comment by colejd** [comment]
Still though, the slider and text might be hard to see. They should probably get a background like we did with the play button.

**Comment by djjcast** [comment]
Sorry for the confusion, but I was referring to the circular progress indicator and time to the right of it in the inline video view: https://i.imgur.com/fJa0rH5.png Looking closely at the OP video, I can barely see the progress indicator filling up and can't make out the time at all.

Another small UI improvement would be to use a monospaced font for the time indicators to prevent them from slightly growing and shrinking over time.

**Comment by ccrama** [comment]
Ah gotcha. My issue with a background is it obstructs the view for the gif below it, but I don't know if there's a better way to make it more visible. What if I did a gradient up from the bottom that gave it a little more contrast?

As for monospaced, great idea about to push those changes!

**Comment by djjcast** [comment]
What about adding a circular transparent black background behind the progress indicator that is slightly bigger than the progress indicator? A similar rectangular background could be added behind the countdown time. Maybe black on white like the smaller content tag might make them easier to see?

**Comment by ccrama** [comment]
![img_6424116cefb5-1](https://user-images.githubusercontent.com/3819844/45919317-23652c80-be59-11e8-90ba-a00b28d85bce.jpeg)
 👍 👎 ? @djjcast @colejd

**Comment by djjcast** [comment]
👍 That looks like it will make the indicator/time easier to see on a light background. Here's a good link to test the new look on: https://www.reddit.com/r/mechanical_gifs/comments/9hrywi/how_an_n64_analog_stick_works/

What do you think about adding a setting for the user to choose to show:
a. Only the progress indicator
b. Only the countdown time
c. Both the progress indicator and countdown time?

**Comment by ccrama** [comment]
Coincidentally that link exposed a pretty big bug @djjcast with the video preview code, will push a fix for that soon :P 

As for the setting, I feel like that is a little niche for our case is there a reason not to have both of them present? I like the transition from "loading" to "playing" that it shows

**Comment by djjcast** [comment]
Oh yeah, I forgot about the pulsing animation that appears while the video is loading. Looking at the screenshot you posted, I was just thinking about how the progress indicator and countdown time provide similar information. The motivation behind the idea was to give the user the option to have a more minimalist look by only showing the indicator or a more utilitarian look by only showing the time. I personally don't mind having both showing - it was just an idea I had looking and your screenshot.

**Comment by ccrama** [comment]
I will look into that, could you please make a new issue for it? Thanks!
