### ISSUE TITLE
Drawer keyboard sometimes graphically glitches/freezes

### ISSUE THREAD

**Issue by djjcast** [ccrama/Slide-iOS#493]
This issue happens rarely and I haven't found a way to reproduce it. See https://gfycat.com/PettyGloriousCero. Dismissing the keyboard by scrolling through the list of subreddits in the drawer caused the keyboard to stop glitching when it came back up.

**Comment by colejd** [comment]
I don't think we have any control over this. Smells like an iOS bug.

**Comment by ccrama** [comment]
Yeah it's iOS unfortunately

**Comment by djjcast** [comment]
Okay, I found a couple sources suggesting the issue might be caused by having zoom enabled:

https://www.theipadguide.com/faq/why-are-letters-my-ipad-keyboard-freezing
https://appletoolbox.com/2016/09/iphone-keyboard-lag-not-working-fix/#Turn_OFF_Zoom

I had zoom enabled for the "Low Light" screen filter. Since I no longer use the screen filter, I'll disable zoom and see if I still notice the issue. FYI, Slide is the first app where I've consistently (although rarely) noticed this issue - I initially thought the issue might be caused by having the keyboard popup automatically.

**Comment by ccrama** [comment]
Let me know if that zoom fixes your problem @djjcast ! Although I believe that is coincidence that it was happening in Slide

**Comment by djjcast** [comment]
Unfortunately, disabling zoom didn't resolve the issue. It's not a big deal - I just wanted to document the issue in case there was an easy fix.
