### ISSUE TITLE
Two-finger swipe for going between posts and subs is very hard to do

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#494]
Since the update to gestures, anyway. I think this would be relatively straightforward to fix -- just require the two-finger swipe to fail for the 1-finger swipe to be recognized.

**Comment by ccrama** [comment]
Unfortunately that does not fix it. There's another issue at play I believe

**Comment by colejd** [comment]
Oof ouch owie my project complexity

**Comment by ccrama** [comment]
Actually I was doing it to the wrong views :P should be fixed in a sec

**Comment by colejd** [comment]
https://www.reddit.com/r/slide_ios_beta/comments/ak0afh/bug_two_finger_swipe_not_always_working/

**Comment by ccrama** [comment]
Not applicable anymore
