### ISSUE TITLE
Slide crashes after being jettisoned from RAM?

### ISSUE THREAD

**Issue by blubov** [ccrama/Slide-iOS#495]
Hello...

Forgive me if this is a repeat, or not phrased well.

On my iPad Pro 2nd Gen 12.9”, if I use Slide for a while, and then use multiple other apps for a while, and then try to use Slide again, it will attempt to relaunch with a black screen, and then immediately crash back to the Home screen. If I immediately relaunch, it will launch as if I’d gone to the app switcher and swiped it out. 
This only happens if I’ve used multiple other apps between uses of Slide. Maybe its a resuming thing, a RAM usage thing...I don’t know. But it happens multiple times per day.

Hope this helps...I’m happy to give whatever other details you think might be useful

**Comment by colejd** [comment]
Interesting. Are you on the latest App Store version, or are you building from source?

**Comment by blubov** [comment]
The latest App Store build...the only way I know how to do it.

**Comment by blubov** [comment]
Ive attached a gif of the event, in case I’d been unclear.

![384b15ac-f758-442a-8f7c-8b42fb0518a6](https://user-images.githubusercontent.com/43453104/45850317-9b214300-bd03-11e8-9f06-47b0716a1132.gif)

**Comment by colejd** [comment]
This may be an odd question, but could I see a screenshot of Slide right where it sits when you first open the app? We're having trouble reproducing this, so I want to find out if there are any specific settings that may be causing the crashes.

**Comment by blubov** [comment]
![449e7b7e-30af-4380-9b95-0b2b1cad6cad](https://user-images.githubusercontent.com/43453104/45855514-75556780-bd1e-11e8-96ae-ed48ff06702a.jpeg)

**Comment by blubov** [comment]
I have it set to go directly to front page on launch.

**Comment by colejd** [comment]
Thank you! I’ll do some research.

**Comment by colejd** [comment]
@ccrama do we have any way to retrieve logs?

**Comment by blubov** [comment]
Hi again...
FYI...1.4 does not resolve the crash previously noted on iPad. 
Is there anything I can do to help resolve the issue?

**Comment by ccrama** [comment]
I believe this is fixed in v2.0, if not feel free to re-open it
