### ISSUE TITLE
Drawer accessible in subreddit and comments view after device rotation

### ISSUE THREAD

**Issue by djjcast** [ccrama/Slide-iOS#498]
The device was rotated to landscape and back to portrait before recording these videos:

https://i.imgur.com/x187fRH.mp4
https://i.imgur.com/ro3r5zO.mp4

**Comment by ccrama** [comment]
How did you open the drawer in that video?

**Comment by djjcast** [comment]
The drawer was opened by swiping up on the bottom bar. The drawer is only accessible like this after the device is rotated - for example: https://i.imgur.com/7grkrl9.mp4 It's as if rotating the device activates a swip gesture on the subreddit and comments bottom bar that reveals the drawer.

**Comment by ccrama** [comment]
Fixed!
