### ISSUE TITLE
Video player somtimes fails to replay from begining when it reaches the end

### ISSUE THREAD

**Issue by djjcast** [ccrama/Slide-iOS#502]
Anecdotally, I've notice that setting `actionAtItemEnd` to `AVPlayerActionAtItemEnd.none` reduces the chance of the video player failing to replay.

Here's an interesting observation made in another reddit iOS client: https://github.com/awkward/beam/blob/f2d62f3d90a228f251c034ea7daf3dabbe64fbb3/Beam/Extensions/AVPlayer%2BPlaybackControls.swift#L15 I couldn't find any official documentation to support this claim but it would explain the failed replays if true.

**Comment by ccrama** [comment]
Might as well try it! Let me know if the issue is still not fixed from the latest source

**Comment by djjcast** [comment]
Okay, I'll test it out. There's another "rewind" `seek` here: https://github.com/ccrama/Slide-iOS/blob/0bc8f53cf05647e1918764686d12535c01e43426/Slide%20for%20Reddit/VideoMediaViewController.swift#L491

**Comment by ccrama** [comment]
Fixed as well @djjcast !
