### ISSUE TITLE
Request: Custom URL Scheme

### ISSUE THREAD

**Issue by amandaoneal** [ccrama/Slide-iOS#504]
I would love for you to add a custom URL scheme ([this thing](https://developer.apple.com/documentation/uikit/core_app/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app)) for Slide iOS - if you could add one in a future update, that would allow apps to link directly into your app's content. Specifically, something like slide://reddit.com/whateverSpecificPost would open that Reddit post in your app. Thanks for considering!

**Comment by ccrama** [comment]
Try it out ;) that's already in the app
