### ISSUE TITLE
Remove search option in "..." menu and integrate in nav menu

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#510]
Right now we have a search button in the "..." menu, which then brings up a modal asking for a string and whether you'd like to search all of Reddit or just the current subreddit. We also have a "search Reddit" option that pops up in the nav menu when you type something in. Since the latter duplicates half of the functionality of the former, I think we should just add a "Search <current subreddit>" option to the latter and outright remove the former. That would make the nav menu feel a little more unified IMO.

**Comment by ccrama** [comment]
So one thing that might make this hard to use is the fact that it shows sub suggestions above search currently. That goes away when you type a first space, but discoverability of this feature needs to be made easier

**Comment by colejd** [comment]
[We have now committed to doing this for 2.0.](https://www.reddit.com/r/slide_ios/comments/9mg0ez/request_unified_search/e7ebukh)
