### ISSUE TITLE
Rotating a video will cause it to pause (occasionally)

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#511]
Not sure if this is even something we can control given the state of the official YouTube library, but we should look into it.

**Comment by ccrama** [comment]
Actually, any video does this as well. Maybe just do a .play() when the rotation finishes?

**Comment by ccrama** [comment]
There are actually a few other times where the pause button messes up. Seems to me that there might be one cause for all of it?

**Comment by ccrama** [comment]
Should be fixed now
