### ISSUE TITLE
When dismissing a website with a video, the audio still plays

### ISSUE THREAD

**Issue by blubov** [ccrama/Slide-iOS#512]
Hello!
Here’s the scenario...
If you open a post that links to a website that has a video on it, and you start playing the video...if you dismiss the window (by tapping outside of it) while the video is playing, the window will go away but the audio will still play.

https://reddit.com/r/news/comments/9j3gdq/charges_dropped_against_woman_who_took_in/

I’ve deleted and redownloaded Slide just to make sure it wasn’t a bad install or something. Happens every time.

**Comment by ccrama** [comment]
Hello! What browser settings are you using in Settings > Link Handling?

**Comment by blubov** [comment]
![3e00251b-36bf-409e-ab62-6e161d375c06](https://user-images.githubusercontent.com/43453104/46166231-b1c61d80-c260-11e8-8a1d-040fdb1a90b4.png)

**Comment by ccrama** [comment]
Fixed for 2.0!
