### ISSUE TITLE
Collapsing parent comment takes you to top of thread

### ISSUE THREAD

**Issue by lowgigs** [ccrama/Slide-iOS#52]

**Comment by ccrama** [comment]
Any steps for reproduction? Not seeing that on my 6s

**Comment by lowgigs** [comment]
No specific steps, but in the picture I circled a comment that is doing this for me.

http://imgur.com/KBM44bh

**Comment by lowgigs** [comment]
https://vid.me/gM9Jm

Not sure if it's normal behavior, but here is a screen recording

**Comment by ccrama** [comment]
Should be fixed in Alpha 4
