### ISSUE TITLE
Add option to play videos on tap and show fullscreen (media view), streaming

### ISSUE THREAD

**Issue by djjcast** [ccrama/Slide-iOS#527]

**Comment by colejd** [comment]
Sorry, but I'm not quite sure what you mean by this. Could you please clarify?

**Comment by djjcast** [comment]
With card view and full banner images set, when you choose "Play videos on tap", the videos play inline. After a video is playing inline, you can tap on it to show it "fullscreen". I'm suggesting adding an option to immediately play videos "fullscreen" on tap. So you would have "Play videos on tap (inline)" and "Play videos on tap (fullscreen)".

**Comment by ccrama** [comment]
That is the same as disabling autoplay @djjcast

**Comment by djjcast** [comment]
Yeah, but the videos are downloaded instead of streamed when "Never autoplay videos" is selected. "Play videos on tap (fullscreen)" would act like "Never autoplay videos" but stream the content instead of download.

**Comment by colejd** [comment]
@ccrama I think we can do this without adding another setting. What if on "never autoplay videos", we leave streaming on but give the cell the existing styling where we just show a still from the video? That would accomplish the task while separating streaming behavior from autoplay behavior, which shouldn't be linked anyway IMO.

**Comment by ccrama** [comment]
What about data conscious users though? I feel like downloading gives an actual advantage to those users, just my two cents

**Comment by ccrama** [comment]
This is the default behavior in 2.0
