### ISSUE TITLE
Slide splash page on iPhone 7+ is off center

### ISSUE THREAD

**Issue by Shiz0id** [ccrama/Slide-iOS#53]
http://imgur.com/a/tWjVP

**Comment by jglass071** [comment]
Offset for me too in both portrait and landscape. iPad Pro 9.7 iOS 11

**Comment by rebel1804** [comment]
I'm experiencing a similar issue on iPhone SE. The splash screen us offset to the lower right.
![image](https://user-images.githubusercontent.com/8388331/28295945-b873e99a-6b32-11e7-8d90-1d9085522596.jpg)

**Comment by jglass071** [comment]
In my iPad it’s to the top left instead of right
![img_0431](https://user-images.githubusercontent.com/18504622/28303366-b6793d36-6b8a-11e7-92ca-a0dec6a1592e.PNG)

**Comment by jglass071** [comment]
On my iPad it’s in the top left
![img_0431](https://user-images.githubusercontent.com/18504622/28303409-f14e1cce-6b8a-11e7-93a9-64c8da26a099.PNG)

**Comment by ccrama** [comment]
Fixed on all devices
