### ISSUE TITLE
Album-image download-progress indicator not updating

### ISSUE THREAD

**Issue by djjcast** [ccrama/Slide-iOS#530]
See https://i.imgur.com/3QoKxEx.mp4.

I think calling the following line within a `DispatchQueue.main.async` block should resolve the issue:
https://github.com/ccrama/Slide-iOS/blob/bdb7b6fa88185cc2b3a42aeaf338c1714bb49fb5/Slide%20for%20Reddit/ImageMediaViewController.swift#L234

Also, do you think submission cell images ("Full image", "Cropped image", and "Thumbnail only") would benefit from having a download progress indicator? For large images, the app can seem unresponsive because there is no feedback as the image downloads - especially on subs like /r/wallpapers.

**Comment by ccrama** [comment]
Great find, I'll look into this! 

I don't think the images should though, too many moving parts and complication of views in my opinion. But if you disagree I would be interested in seeing what an implementation of this could be

**Comment by ccrama** [comment]
Fixed, and @colejd did a pulsing animation while loading. What do you think?

**Comment by djjcast** [comment]
Okay, I just installed the latest version - the last version I had install was from [Oct 2](https://github.com/ccrama/Slide-iOS/commit/eedb75a6c2e3420b2e5679f1d441cdfb4477bf6b).

I like the pulsing animation and find it helpful.
