### ISSUE TITLE
Add notifications

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#537]
Right now the notifications section in options says "Coming soon!"

**Comment by ccrama** [comment]
I honestly don't think they are coming. It did not work well on the TF versions because we can't guarantee a check

**Comment by colejd** [comment]
Well, we need _something_, right? There's no notifications at all right now. If we can't control the interval we can at least support it a little.

**Comment by colejd** [comment]
We can definitely do this with [silent notifications](https://medium.com/@m.imadali10/ios-silent-push-notifications-84009d57794c). They're notifications that don't actually cause anything to pop up, but they wake up the app for up to 30 seconds. That's enough time to query the API for new messages and dispatch an actual push notification if they have a new message.

**Comment by ccrama** [comment]
With what server @colejd ?

**Comment by colejd** [comment]
Whoops, missed that detail. Blame my job for always including a backend with our apps lol. Why not use [background fetch](https://developer.apple.com/documentation/uikit/core_app/managing_your_app_s_life_cycle/preparing_your_app_to_run_in_the_background/updating_your_app_with_background_app_refresh) then?

**Comment by ccrama** [comment]
We did, but I removed it because Apple almost never let it run. Did you ever get notifications during TF?

**Comment by ccrama** [comment]
Doneeee

**Comment by ccrama** [comment]
But see #575
