### ISSUE TITLE
Half Screen on Landscape

### ISSUE THREAD

**Issue by nusm** [ccrama/Slide-iOS#54]
When I turn my phone to landscape mode on frontpage, all the posts are on the left half of the screen, and the right half is white. If I select a post, it opens full screen in landscape, but when I swipe back to the frontpage, I get the half screen again.

I'm using an iPhone 7 with latest iOS 10.3.2

**Comment by ccrama** [comment]
Landscape hasn't been done yet, see #36 which applies to iPhones as well

**Comment by jglass071** [comment]
I’m getting this issue too, noticed when changing from landscape to portrait on my iPad Pro 9.7. Seems any change in orientation when the app is open causes some problems. Restart of app fixes the problem.
