### ISSUE TITLE
Issue w/ Emoji in Links

### ISSUE THREAD

**Issue by xnaas** [ccrama/Slide-iOS#543]
Last night I stumbled across [this Reddit post](https://www.reddit.com/r/firefox/comments/9mjwbi/calls_between_javascript_and_webassembly_are/) on /r/firefox which links to:

`https://hacks.mozilla.org/2018/10/calls-between-javascript-and-webassembly-are-finally-fast-🎉/`

That's all well and fine but for some reason Slide converted the emoji weird and spit out this link:

`https://hacks.mozilla.org/2018/10/calls-between-javascript-and-webassembly-are-finally-fast-%25F0%259F%258E%2589/`

But the link should be:

`https://hacks.mozilla.org/2018/10/calls-between-javascript-and-webassembly-are-finally-fast-%f0%9f%8e%89/`

The issue appears to be with Slide specifically as every other app I've tried opens the emoji link normally.

**Comment by colejd** [comment]
Thank you based Unicode

**Comment by xnaas** [comment]
🙃

**Comment by ExE-Boss** [comment]
This also occurs in the official Reddit app. 🤦🏻‍♂️

**Comment by ccrama** [comment]
Fixed in beta 2!
