### ISSUE TITLE
Rubber band subreddit list in switcher

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#547]
We previously turned it off because rubber banding was interfering with the logic that allows the switcher to be swiped down from anywhere if the scroller was at the top. However, I've seen this work in one of Apple's own apps, so there must be a way we can do this.

**Comment by ccrama** [comment]
Unfortunately it's still an issue, in the apple apps sometimes it gets stuck rubberbanding and not swiping and I feel like that would be a step back

**Comment by colejd** [comment]
When we get to this, let's look into ways that we can prevent rubberbanding along the top.

**Comment by ccrama** [comment]
Not applicable anymore imo
