### ISSUE TITLE
Implement new photo picker for uploading images

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#552]
iOS has one built-in. We should just use that.

This would technically fix the issue where things are paging strangely, as in [this thread](https://www.reddit.com/r/slide_ios/comments/9mrd00/bug_two_issues_with_photo_selection_and_uploads/).

**Comment by ccrama** [comment]
I fixed the paging issue. Issue with the iOS picker is no multi select so this is a wontfix
