### ISSUE TITLE
Preload next and previous images when scrolling through imgur albums

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#553]
This would make things much, much smoother. Users would only see loading activity if they're going very fast or if network is slow.

**Comment by ccrama** [comment]
So what is happening is we only create the VC when it's being swiped to. This would require us to pre-create all the VCs and keep them in memory. I don't think the trade offs are worth it in this case

**Comment by colejd** [comment]
You don’t need to do every page. Just the two adjacent pages. Many apps do this and I know we can find a good way to do it.

**Comment by ccrama** [comment]
It is doing this now afaik
