### ISSUE TITLE
(Suggestion) Filter all photos from a subreddit 

### ISSUE THREAD

**Issue by MercuryXIII** [ccrama/Slide-iOS#558]
Meaning remove them. I hate seeing all the I bought a new iPhone posts

**Comment by colejd** [comment]
Closing since you appear to have gotten an answer on the subreddit. For future visitors: you can do this by pressing the "..." button and tapping "Filter content". This lets you filter out images, albums, gifs, videos, links, selftext posts, and nsfw posts.
