### ISSUE TITLE
Unread tab in inbox infinitely clones unread comment

### ISSUE THREAD

**Issue by Shiz0id** [ccrama/Slide-iOS#56]
https://imgur.com/gallery/8iYC8

**Comment by ccrama** [comment]
Ah, does it keep trying to scroll to load more?

**Comment by Shiz0id** [comment]
Yes, it just keeps reloading. I'm unsure of the behavior if there are multiple unread messages

**Comment by ccrama** [comment]
No longer an issue, view was re-written
