### ISSUE TITLE
Make color change for already-read submissions more dramatic

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#560]
The styling we apply to already-read submissions is hard to discern on bright themes, as noted here:
https://www.reddit.com/r/slide_ios/comments/9n99pz/question_great_app_one_question/e7x1q0u

Perhaps we should make the post itself a little darker/lighter depending on the theme?

**Comment by colejd** [comment]
I like that idea.

**Comment by ccrama** [comment]
Issue would be with AMOLED themes

**Comment by colejd** [comment]
We might be able to get away with that if we just make the text color difference more dramatic.

**Comment by colejd** [comment]
Done!
