### ISSUE TITLE
iOS auto lock settings ignored while app is open

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#561]
https://www.reddit.com/r/slide_ios/comments/9oe384/bug_ios_auto_lock_settings_ignored_while_app_is/

**Comment by ccrama** [comment]
I can't reproduce this, we only do this in the video view and disable it in didDisappear. Can you @colejd ?

**Comment by ccrama** [comment]
I believe we have done a lot of video improvements and this probably isn't an issue anymore. Feel free to re-open if this surfaces again!
