### ISSUE TITLE
Bottom nav bar can get stuck in incorrect state

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#564]
Sometimes when restoring the app from the background, the bottom nav bar can get stuck in a weird state. Like the regular "minimized" state is treated as the "large" state, and then when you scroll, the bar and icons get even smaller. On an iPhone X, this makes the menu impossible to interact with because of the home bar. It won't resolve unless you restart the app.

Assigning this to 2.0 since this is happening a lot to a major part of the UI.

**Comment by ccrama** [comment]
I have not run into this, can you provide a video of it happening?

**Comment by colejd** [comment]
Haven't seen this in some time. Let's reopen this if it happens again.
