### ISSUE TITLE
Allow setting submission title to appear above images in Submission Layout

### ISSUE THREAD

**Issue by rkaregaran** [ccrama/Slide-iOS#566]
There doesn’t seem to be a way to update the submission layout to force submission titles to appear above an image. When scrolling through submissions, it’s hard to gain context because while you’re scrolling, the text would only appear after you’ve seen the image instead of before. 

Showing the text before the image would would hint context to the user as the image is being revealed by scrolling. 

#request

**Comment by colejd** [comment]
This can be done in settings -> submission layout -> Submission view mode and setting it to “centered card view”. There’s definitely something to be said about making this more discoverable, though.

**Comment by rkaregaran** [comment]
That did the trick. I remember being confused about how the submission view modes are different. Thank you!
