### ISSUE TITLE
Titles not wrapping, are cut off

### ISSUE THREAD

**Issue by ephlodia** [ccrama/Slide-iOS#58]
What the title looks like from front page:
![img_1728](https://user-images.githubusercontent.com/21162665/28286355-c147483c-6aec-11e7-9f9d-2ae2f00f9357.PNG)

The actual title:
![img_1729](https://user-images.githubusercontent.com/21162665/28286373-d11873a8-6aec-11e7-83b0-cfb0ab598184.PNG)

**Comment by ccrama** [comment]
Are there any two-line titles you have run across? Also what's your device and iOS version?

**Comment by ephlodia** [comment]
Those work fine, strange enough. 

iPhone SE 10.3

**Comment by ccrama** [comment]
Those are actually both correct, they aren't cut off
