### ISSUE TITLE
Adjust font baselines for post flair

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#581]
As-is, the text is vertically off-center. Depending on the font used (test Avenir vs. System), this means either the flair text is vertically off-center relative to its background, or that the text is centered but the background and text are off-center compared to the title.

Put more simply, let's make sure that the the following are true:
1. Flair is centered vertically relative to title text baseline
2. Flair text is centered relative to flair background

**Comment by ccrama** [comment]
Should not be a problem with the new library!
