### ISSUE TITLE
"Download Image" button in image modal sometimes locks up the app

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#588]
Sometimes the download function doesn't complete successfully, or takes forever. This is problematic when the operation locks up the UI indefinitely. We should prevent this from locking up the UI at the very least.

@ccrama are we downloading the image again when we do this, or are we saving the image already displayed?

**Comment by ccrama** [comment]
We are saving the already loaded image and then telling the Camera Roll to import that image. There is nothing thread blocking going on 

`        if let image = imageView.image {
            CustomAlbum.shared.save(image: image, parent: self)
        } 
`

**Comment by ccrama** [comment]
I made it save on an async thread which should solve the issue either way!
