### ISSUE TITLE
Audit for landscape mode compatibility

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#590]
We need to go through and make sure everything looks good in landscape. Let's add things to this issue that need fixing as we go.

- [ ] Properly offset for safe areas in SingleSubredditViewController in landscape

**Comment by ccrama** [comment]
Hijacking this issue, iPad bottom drawer is wrong size in split mode

**Comment by ccrama** [comment]
I fixed my issue, did your PR close the rest of this?

**Comment by colejd** [comment]
Sure did.
