### ISSUE TITLE
3rd gen iPad Pro support

### ISSUE THREAD

**Issue by fakebanana** [ccrama/Slide-iOS#597]
There are many problems running Slide on the 3rd generation 12.9 iPad Pro:

* After running the first time, Slide immediately crashes on launch
* The buttons on the bottom aren't visible (they still work, but you can't tell the buttons are there because the bar is almost completely cropped off)
* Multi-column mode doesn't work (regardless of setting, only one column shows up portrait or landscape)

**Comment by f6310** [comment]
I want to add to this. Removing the app, restarting the iPad and redownloading from the App Store does not resolve.

**Comment by colejd** [comment]
@ccrama just bought an iPad Pro. Count on this getting fixed for the next update.

**Comment by ccrama** [comment]
I didn't notice any issues, so I guess they have been resolved already with the 2.0 changes ;)
