### ISSUE TITLE
Crash when pressing Guest in sidebar to sign in

### ISSUE THREAD

**Issue by jglass071** [ccrama/Slide-iOS#62]
When I open the sidebar and tap Guest trying to sign in the app crashes every time.
iPad Pro 9.7 iOS 11

Edit - happens in both portrait and landscape, also checked with orientation lock on and off.

Gif https://gfycat.com/gifs/detail/SimplisticElasticBluebottle

**Comment by ccrama** [comment]
I'm about to pick up an iPad pro so I'll see if I can reproduce it, thanks!

**Comment by ccrama** [comment]
Fixed, was all related to an iPad issue
