### ISSUE TITLE
Use swipe from anywhere everywhere except where we provide user options to avoid it

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#624]
What I mean by this is that we have several screens in the app that don't have gesture recognizers that would conflict with the sloppy swiper, such as the settings screen. It'd be a general improvement for ergonomics if we used the sloppy swiper in those screens.

An alternative name for this is "always use sloppy swiper in settings screens".

**Comment by ccrama** [comment]
Done, now it's in every VC except ones with paginating content (inbox, etc)
