### ISSUE TITLE
Only autoplay when video is centered onscreen

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#627]
https://www.reddit.com/r/slide_ios/comments/9y1wqj/request_centered_autoplay_for_videogif/

**Comment by colejd** [comment]
Personally, I would change it to be "autoplay under one the following conditions":
- Bottom of video is onscreen
- Video is centered onscreen

Whichever is first.

**Comment by ccrama** [comment]
Imo this is not feasible, we would have to write a completely new scroll watcher and redo a ton of the autoplay logic

**Comment by colejd** [comment]
You sure? Can't we pull this off by just holding off on calling `videoPlayer.play()` until it gets called externally? I'd imagine we'd have to add some new scrolling logic, but not a lot.

**Comment by ccrama** [comment]
Now it's not when centered, but when displayed which I think checks all our boxes. Centered would not work with multicolumn!
