### ISSUE TITLE
Over time, top bar drifts down while bottom bar gets taller

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#634]
https://www.reddit.com/r/slide_ios/comments/9zsfk0/bug_the_top_bar_slowly_gets_lower_and_lower_and/

**Comment by ccrama** [comment]
Looks like that NavigationController thing we fixed a few weeks ago? 🤔

**Comment by ccrama** [comment]
I have not noticed this at all post v2.0
