### ISSUE TITLE
Gifycat made change breaking gif loading

### ISSUE THREAD

**Issue by scot-onet** [ccrama/Slide-iOS#636]
Unknown cause but multiple reddit browsing apps have the same issue, including slide_ios beta 68.  Some other apps have resolved via updates. 

Example : https://reddit.com/r/titanfall/comments/62lokb/an_execution_so_well_timed_it_should_have_been_in/

Will load low res placeholder but will not complete loading of gif.

**Comment by colejd** [comment]
I've looked into this and can verify. If you go to the API endpoint we use for that link (`https://gfycat.com/cajax/get/ComfortableHelpfulBullfrog`), it appears to return `Not Found`.

I wonder how the other apps ended up fixing it. This seems to be a problem completely on Gfycat's end. Maybe they switched to use the mirror that Reddit hosts?

**Comment by colejd** [comment]
[Hot off the presses](https://old.reddit.com/r/baconreader/comments/a11jud/not_able_to_view_gfycat_links/)! This is hearsay until we get an official announcement, but it appears that Gfycat has deliberately removed the endpoint.

**Comment by ccrama** [comment]
Has been fixed for the build waiting for approval
