### ISSUE TITLE
Fix misc crash reports

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#639]
- [ ] Opening the link in this post crashes Slide: https://amp.reddit.com/r/hockey/comments/a2k5q3/larkin_grabs_calvert_from_the_bench_bertuzzi/
- [ ] Opening this URL crashes Slide: https://m.gamer.com.tw/forum/C.php?bsn=26742&snA=54852&bpage=1&ltype=&page=45
- [ ] Uploading a photo to Imgur from a reply crashes Slide

**Comment by ccrama** [comment]
Can't reproduce 3

**Comment by ccrama** [comment]
I think these are all fixed
