### ISSUE TITLE
#bug No icon/color coding when second swipe option disabled

### ISSUE THREAD

**Issue by technolojesus** [ccrama/Slide-iOS#640]
In the comment gesture options when I disable the second swipe option, and have the first set to upvote / downvote no visual cues show up. The voting action works as expected, but there is just a dark overlay. 

P.S. The app is awesome! Thank you :-)

**Comment by ccrama** [comment]
What build of Slide are you on? At the bottom of settings 

And thank you :)

**Comment by technolojesus** [comment]
2.0 build, 70. No worries, glad to help.

–PM

**Comment by ccrama** [comment]
Fixed! There were actually quite a few logic problems with the comments code but I think I have sorted it out

**Comment by technolojesus** [comment]
Nice! I always find it kind of satisfying to get one before it actually bites me in the ass :-)
