### ISSUE TITLE
Title filters not working

### ISSUE THREAD

**Issue by technolojesus** [ccrama/Slide-iOS#642]
I’m unable to get post title filters to work. Filters get added to the list, but none seem to be applied. I’ve tried refreshing and restarting, short and long keywords, but no luck. 

I’m on 2.0, build 70.

**Comment by ccrama** [comment]
Do the terms you are trying to filter have spaces by chance?

**Comment by TwinXM** [comment]
I’m having the same problem. No spaces. Some of my filters are using () or []. Nothing is being filtered.

**Comment by ccrama** [comment]
Fixed in v2.1
