### ISSUE TITLE
iPad AlertControllers need frame set

### ISSUE THREAD

**Issue by jglass071** [ccrama/Slide-iOS#65]
Such as any of the sub menus under Main Theme, and pressing the dotted line in the sidebar.
Edit; and menu icon in top right on main screen

**Comment by ccrama** [comment]
That is strange, not able to reproduce any of these. Is this on your iPad as well?

**Comment by jglass071** [comment]
Yes it is. Happens in both landscape and portrait orientations

**Comment by nathankov** [comment]
I am getting the same thing on 10.5 pro on iOS 11. Cannot sign into my Reddit account or change app settings. These functions work on my iPhone 7 also with iOS 11.

**Comment by ccrama** [comment]
Fixed all of them (over 100 D:)
