### ISSUE TITLE
Comment count and post score misaligned

### ISSUE THREAD

**Issue by jglass071** [ccrama/Slide-iOS#66]
Happens in both landscape and portrait
iPad Pro 9.7 iOS 11
![img_0426](https://user-images.githubusercontent.com/18504622/28287240-cbd1a932-6b32-11e7-8049-7913f7c8d8ba.PNG)

**Comment by ccrama** [comment]
Does that only occur with thumbnail mode enabled?

**Comment by jglass071** [comment]
Yes - they are fine with Hide Banner Image disabled

**Comment by ccrama** [comment]
Should be fixed!
