### ISSUE TITLE
Add ability to view account / inbox from more places

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#663]
Specifically the comments VC and SingleSubredditVC. This might go toward a broader discussion on whether we could make the bottom nav drawer available in more places.

**Comment by ccrama** [comment]
I can't think of a place that doesn't already have a navigation bar for that specific context. I think I will veto this one because it doesn't make sense to go to inbox outside of the base context

**Comment by colejd** [comment]
What about switching accounts? I run into this frequently.

**Comment by ccrama** [comment]
That will be something for replies/comments, but the UI flow would have them go to the main page to do this anyway (we would have to restart MainVC anyway)
