### ISSUE TITLE
Add option for forcing thumbnail/image clicks to open the post instead of the media

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#675]
This is a user request: https://www.reddit.com/r/slide_ios/comments/a7z3st/question_trying_out_slide_on_my_new_ipad_and_one/

I think it makes sense. On iPad, the post view is typically big enough to show the media and the comments. This would just be a convenience thing to "skip a step", so to speak.

**Comment by ccrama** [comment]
Done!

**Comment by colejd** [comment]
I had it backward. It's only for banner images. I think the intent of the post (and my own intent) is that any tap on a banner or thumbnail would always open the comment view. Essentially this is turning off the media modal / browser opener for link cells.

**Comment by colejd** [comment]
Also an aside, but the setting might go better in Link Handling or General.

**Comment by colejd** [comment]
Per our discussion, let’s make this work for all banner media and call it a day.

**Comment by ccrama** [comment]
That was done in v2.0
