### ISSUE TITLE
Cant listen to music and browse slide at same time

### ISSUE THREAD

**Issue by shingly** [ccrama/Slide-iOS#685]
I'm not sure if its a bug, setting or intended feature but I'm pretty certain its a bug. I'm trying to browse reddit with my headphones and listen to music. I started listening first in Apple Music and switched apps to Slide and instantly the music paused, there was no videos playing within Slide just text posts. I resumed the music but each time I come back to Slide it stops. I played around with the settings but nothing has fixed it. I understand that if i where to be listening to music while using slide and selected a video, the music should pause while the video plays and once the video ends the music should resume.

**Comment by ccrama** [comment]
Should be fixed in v2.1.2 which will be out soon!
