### ISSUE TITLE
Frequently crashes

### ISSUE THREAD

**Issue by shingly** [ccrama/Slide-iOS#686]
Im really not sure what the cause is. But this app crashes over and over for me on an iPad Air 2 and iPhone 6 both on iOS 12.1.1. I have tried reinstalling but it still happens. I open the app and choose any random subreddit and scroll around and within a minute it crashes. I havent been able to keep it open for longer then 4 minutes. But i do now that if i go to any subreddit and sort by top/all it crashes instantly everytime.

**Comment by shingly** [comment]
That fixed it! I set videos to never autoplay and cleared cache and there is no more crashing.

**Comment by ccrama** [comment]
I can't really do much without being able to reproduce the issue, if you are able to find a pattern please let me know! FWIW I'm not running into crashes, might be setting related

**Comment by ccrama** [comment]
We have fixed a ton of memory issues and done a lot of performance improvements for v3.0! If this re-surfaces, feel free to re-open
