### ISSUE TITLE
Allow post sliding, shadowbox, and gallery view to load new posts

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#688]
https://www.reddit.com/r/slide_ios/comments/a8ityr/bug_slide_between_posts_stops_working_for_me/

This is something we need to address soon, I think. Right now the shadowbox, gallery view, and just swiping between posts using the two finger gesture doesn't cause new posts to be loaded when you reach the end of the currently loaded posts.

**Comment by colejd** [comment]
Done for shadowbox. Did you do this for Gallery mode, @ccrama?

**Comment by colejd** [comment]
Also post sliding?

**Comment by ccrama** [comment]
Done in v6
