### ISSUE TITLE
Add option for smaller content preview in CommentVC on iPad

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#690]
Seen a few people ask for this for the iPad version. Essentially this would be limiting the height of the content preview so that it doesn't take up more than, say, 50% of the screen's height. Note that what I'm talking about would show *all* of the content, just aspect fitted into a smaller area.

I would propose this would be an on-by-default option. The content can get pretty ridiculously big without some sort of height limiter.

**Comment by ccrama** [comment]
Settings > Comments > Crop image does this, will make it default for iPads though!

**Comment by ccrama** [comment]
Defaulted off for pads

**Comment by ccrama** [comment]
I feel like this would lead to a lot of whitespace though, imagining having like an extended thumbnail but no content on the right side of it
