### ISSUE TITLE
Crashing on when viewing imgur album comments

### ISSUE THREAD

**Issue by mfong1** [ccrama/Slide-iOS#694]
I don’t know if there is something I need to do on my end but it looks like slide crashes whenever I try to view imgur album comments in subs like r/DIY

**Comment by colejd** [comment]
Do you have an album that causes crashing for you every time? 

Could you also tell us the device and iOS version you’re on?

**Comment by colejd** [comment]
Ohhhh, I was confused. Sorry about that. The comments crash has been fixed in a patch that we’re trying to get out in the next few days :)

**Comment by colejd** [comment]
Please feel free to reopen this issue if the problem persists. Thank you for reporting!
