### ISSUE TITLE
Status indicators disappear after opening a video and don’t return until app is restarted

### ISSUE THREAD

**Issue by NanoLynx** [ccrama/Slide-iOS#699]
https://imgur.com/a/LgJJM5i

**Comment by ccrama** [comment]
I was not explicitly disabling it anywhere, so I have just explicitly enabled it to hopefully reverse whatever is hiding it

**Comment by colejd** [comment]
Smells like we’re leaking the video player @ccrama. We don’t explicitly hide or show it — the video modal is the only VC that should be controlling that, and once it’s dismissed that should go back to normal.
