### ISSUE TITLE
Split Screen on iPad

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide-iOS#70]

**Comment by jglass071** [comment]
Assuming what you’re referring to here is the app not resizing when the orientation or resolution changes - here is how it’s working on my iPad iOS 11 https://gfycat.com/gifs/detail/ClearcutSorrowfulLamb

**Comment by ccrama** [comment]
No I was referring to adding split screen mode support to Slide

**Comment by ccrama** [comment]
Yes, what I was referring to

**Comment by ccrama** [comment]
Done
