### ISSUE TITLE
Just lost all of my "read later" posts

### ISSUE THREAD

**Issue by Bloo9** [ccrama/Slide-iOS#700]
I'm assuming this is a bug because issue number #577 mentions caching posts in read later and that issue has already been closed.

Either way, I was using the app and added a bunch of things for later - I think it was at 14 last I checked?
Well I took a break from the app for about ~10 hours and when I came back to the app all of the read later posts were gone!

To be fair, when I opened the app it showed me the splash screen, which means it must have been suspended in the background, which seems to be the culprit for this bug?
If I add some things, leave the app and then come back after like 15 minutes then all of them are there. It seems to only happen if the app gets suspended by iOS and has to reopen again.

**Comment by ccrama** [comment]
Good find! Apparently iOS doesn't call willTerminate if you have background refresh enabled (notifications), and that is where I was saving it. If you force quit, though, it would save. Fixed for the next update!
