### ISSUE TITLE
Modify language on "save draft" alert

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#702]
Right now when you try to discard a comment, it presents a menu saying "yes", "yes and save draft", and "cancel". It would bring it more in line with other parts of iOS if we adjust this so it says "Delete Draft", "Save Draft", and "Cancel". This is more of a UI thing, where you want button titles to be verbs.

We should also change the button from "Discard" to "Cancel".

**Comment by ccrama** [comment]
Done! Anywhere else in the UI you think we should re-name?

**Comment by colejd** [comment]
Nope!
