### ISSUE TITLE
Hide Read Action Button Causes Crash

### ISSUE THREAD

**Issue by jamesallnutt** [ccrama/Slide-iOS#705]
See video example here; https://vimeo.com/309603388

Only seems to occur on Frontpage. 

Other details to note, if some threads remain “unread” crash does not occur. Occurs if all threads loaded on current page are Read. 

Version 2.0.74

**Comment by ericclone** [comment]
Also note that if there are many read posts that are hidden, the first page would contain mostly ads which may not be the intended outcome.

**Comment by jamesallnutt** [comment]
Unless using Reddit Gold / Slide Premium - there would be no Ads, so no content displayed whatsoever. Maybe that is what causes the crash for me? The no content display.

**Comment by ccrama** [comment]
That would be a likely cause @jamesallnutt, will look into it

**Comment by ccrama** [comment]
Should be fixed in 3.0
