### ISSUE TITLE
Space bar with external keyboard scrolls instead of inserting space

### ISSUE THREAD

**Issue by MrClever** [ccrama/Slide-iOS#707]
I use two Bluetooth keyboards (one Belkin the Logitech) with two iPads (both 6th gen). When composing a comment/reply, alphanumeric characters display correctly, but the space bar scrolls a page down in the comments as opposed to inserting a space in the comment text. I’m relatively new to Slide-IOS so not sure if this has been discussed before (I didn’t find any similar issues in the archives).

**Workaround** - turning off the external keyboard and using the on-screen keyboard works as expected.

**Comment by ccrama** [comment]
Good find! Fixed for the next update
