### ISSUE TITLE
Fix spelling for thread

### ISSUE THREAD

**Issue by 9034725985** [ccrama/Slide-iOS#708]
I am just trying out the iOS app (I mainly use Android) and I'd like to see if I can change thead to thread. 

![signal-2019-01-09-165820](https://user-images.githubusercontent.com/1676445/50931257-12ecb800-1430-11e9-8da9-c439bb4e72d5.png)

Not sure how to mark issues as low priority...

**Comment by ccrama** [comment]
Thanks for the fix!
