### ISSUE TITLE
Sync subreddits list from account

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#716]

**Comment by ccrama** [comment]
That is not feasible, it would take over 5 requests just to get my subreddits and that would complete much later than when we build the tab bars, etc. Also, if they use Slide for their redditing it will always be synced

**Comment by colejd** [comment]
I think it's hasty to close it without more discussion. We don't need to sync every time the Main VC is loaded. But I think we could be syncing in more places. What about when the account is changed? We reconstruct everything at that point anyway.

**Comment by ccrama** [comment]
What happens if they remove it from their slide sub list? I think that is enough to axe this

**Comment by ccrama** [comment]
Done in v6
