### ISSUE TITLE
Highlighted comments in night mode not very legible 

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#72]
![img_1735](https://user-images.githubusercontent.com/30244311/28288561-6e6dff72-6af4-11e7-9e56-a90ce09a519d.PNG)

**Comment by incIined** [comment]
![img_1745](https://user-images.githubusercontent.com/30244311/28296010-1950a9c4-6b1a-11e7-81a5-c4566de6f50c.PNG)

**Comment by ccrama** [comment]
Should be fixed now!
