### ISSUE TITLE
Make title positioning settings more obvious in Submission Layout settings

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#721]
"How do I put the title before pictures?" is a question we get a lot. I think this indicates we could make the feature more discoverable.

What if we have a toggle called "Title before content" or something like that? "Submission view mode" seems to be, aside from adjusting the title position, solely responsible for adjusting spacing and margins. I think it would be best to separate them.

**Comment by ccrama** [comment]
The issue with that is the centered view mode is not available for other view types, only the card layout

**Comment by ccrama** [comment]
I changed a lot of wording for v4.0 settings!
