### ISSUE TITLE
Add ability to pick starting subreddit

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#734]
https://www.reddit.com/r/slide_ios_beta/comments/aknceq/bug_build_92_fontpage_and_all_doesnt_reflect_the/ef7vs1m/

**Comment by ccrama** [comment]
I don't think this is really a bug, just how it happens. I mark it as read when didEndDisplaying runs. The logic is super simple and its not worth complicating it imo

**Comment by ccrama** [comment]
Should work now with the new pinned system
