### ISSUE TITLE
Weirdness with specific youtube link

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#741]
https://www.reddit.com/r/Simulated/comments/ahknnp/3d_advanced_neural_network_simulation_computer/

Here's a weird one. The youtube video fails to load, and when you hit the "open in youtube" button, it redirects you to youtube, which then opens chrome to the url `2gl`. Back in Slide, the three-dot menu in the media player doesn't respond to touch events.

If you open the post menu:
1. "Open in safari" will pass the correct URL over to safari, instantly opening youtube (this is all good)
2. "Open in Chrome" will instantly crash the app
3. Both "share content" and "share reddit link" do nothing

If you open the menu that comes up when you long press the video:
1. "Open in chrome" crashes the app
2. "Copy URL" copies the correct URL
3. "Open Externally" properly opens the youtube app with the correct video

**Comment by ccrama** [comment]
This is like a land mine of a URL: https://www.youtube.com/attribution_link?a=zIin679knJs&amp;u=%2Fwatch%3Fv%3D2GYLpzZzqeg%26feature%3Dshare

**Comment by ccrama** [comment]
We had some funky substring logic using arrays for some reason... Have fixed it!
