### ISSUE TITLE
Pressing comment navigation before comments are loaded causes a crash

### ISSUE THREAD

**Issue by LoganSchmalz** [ccrama/Slide-iOS#746]
iPhone 5S, Slide 3.0 build 92

**Comment by ccrama** [comment]
I believe the issue is actually if there are no comments. Fixed!

**Comment by LoganSchmalz** [comment]
After you mentioned the no comments issue, I checked it and it crashed. In beta 93, it no longer crashes with no comments. However, it still crashes when loading comments.

I also wanted to quickly mention I’ve found some inconsistencies in the comment navigation itself but I’m not sure what to tag the issues as, because I’m not sure if it’s a bug/oversight or a design choice.

**Comment by colejd** [comment]
Don’t worry too much about tagging. I can take care of that. That said, I’d call it a bug.

**Comment by LoganSchmalz** [comment]
This is still happening in beta 95 and I think this is the cause: pressing the button once does not crash the app, but pressing it twice does. When I tested this in beta 93 I thought I just wasn’t hitting it the first time and chocked it up to human error.

**Comment by LoganSchmalz** [comment]
Still getting this bug on beta 98, same test procedure as my previous comment. Just click the comment navigation twice while the comments are still loading.

**Comment by ccrama** [comment]
Didn't see your update @LoganSchmalz , thanks for the heads up!

**Comment by ccrama** [comment]
I am actually not able to reproduce this issue, mind posting your comment settings page?

**Comment by LoganSchmalz** [comment]
![img_0857](https://user-images.githubusercontent.com/19539925/52921004-4137a000-32d8-11e9-8221-fc2940c8f61f.PNG)
![img_0858](https://user-images.githubusercontent.com/19539925/52921005-4268cd00-32d8-11e9-9345-26de88324521.PNG)
Sorry for closing and reopening, hit it on my phone by accident.

**Comment by ccrama** [comment]
So the issue is being caused by clicking it the split second between when it's loaded technically but before all the cells are displayed

**Comment by ccrama** [comment]
Fixed it for real this time!
