### ISSUE TITLE
Please move the subscribe/unsubscribe button from where it is. 

### ISSUE THREAD

**Issue by hary585** [ccrama/Slide-iOS#75]
I have accidentally subbed and Unsubbed from subs so many times. 

Even a confirmation would be nice like are you sure you want to unsubscribe. Something of that nature.

**Comment by ccrama** [comment]
It is pretty out of the way already, what is the reasoning for accidentally clicking it? Also it does pop up and ask you if you would like to before it does it

**Comment by hary585** [comment]
I'm used to iOS version of back being in that corner.

Also I for unsubscribe it doesn't prompt when I'm post view

**Comment by hary585** [comment]
The sub/unsubscribe button in post view is what this is about sorry for
miscommunication

**Comment by incIined** [comment]
A prompt would be nice. I've unsubbed from a couple of subs accidentally. 

Or you could make it look like an unsubscribe button, right now it just looks like a "mark as done/read" button or something.

**Comment by ccrama** [comment]
Added a close button on the very left, was necessary for the iPad and worked for the iPhone as well
