### ISSUE TITLE
Feature: Ability to open links in Firefox Focus

### ISSUE THREAD

**Issue by rm-rf-home** [ccrama/Slide-iOS#758]
It's brilliant that opening Links in Firefox is already supported. As I use Firefox Klar as my primary browser on iOS (called "Firefox Focus" in non-German speaking countries), it would be nice to be able to choose this browser for opening links in Slide. Currently only Safari and Firefox can be chosen under "Settings - Link handling".

It looks like the "Focus iOS open in client"-reference is empty though: https://github.com/mozilla-mobile/focus-ios-open-in-client

![img_2015](https://user-images.githubusercontent.com/36776420/52537753-f8c13500-2d61-11e9-930e-0aecc3247c3e.jpeg)

**Comment by ccrama** [comment]
![img_2959](https://user-images.githubusercontent.com/3819844/52538206-55f2c180-2d35-11e9-8839-2ad112d8b9a4.PNG)
Firefox Focus is actually already supported :)

**Comment by rm-rf-home** [comment]
Then I'll probably have to create a new issue because it's not showing for me. Maybe it's because I have "Firefox Klar" installed: https://support.mozilla.org/en-US/kb/difference-between-firefox-focus-and-firefox-klar
