### ISSUE TITLE
iOS status bar needs to have a solid background. 

### ISSUE THREAD

**Issue by medi0crescientist** [ccrama/Slide-iOS#76]
![img_0735](https://user-images.githubusercontent.com/30246837/28293425-16a26ec6-6b22-11e7-8b56-7d3a2071207c.PNG)

**Comment by ccrama** [comment]
That is intended, I think it looks better that way, especially when you scroll up

**Comment by medi0crescientist** [comment]
I've found it kind of distracting so far. Especially if I'm scrolling through posts and take a glance at the time. I guess what I really meant to say is that post' titles and what not should be made to not scroll into the status bar.

**Comment by hary585** [comment]
It looks super messy.

**Comment by rebel1804** [comment]
I see it as the status bar text clashing with the post text, making both illegible. Perhaps the status bar could have a semi-transparent background?

**Comment by ccrama** [comment]
Added semi-transparent one to next update
