### ISSUE TITLE
Not able to choose Firefox Klar for link handling

### ISSUE THREAD

**Issue by rm-rf-home** [ccrama/Slide-iOS#760]
First of all thanks for the great app.

## The problem

I'm not able to choose the browser "Firefox Klar" in the link handling settings. Maybe it has something to do with the fact that "Firefox Focus" support is already in place but in German speaking countries the app is available under a different name "Firefox Klar": https://support.mozilla.org/en-US/kb/difference-between-firefox-focus-and-firefox-klar

## Environment

* Slide version that exhibits the issue: 2.1.2 build 84 (from German App Store)
* iOS version used to run Slide: 12.1.4 (16D57)
* iOS device type: iPhone 7
* Installed Browser: Firefox Klar 8.0 (from German App Store)

![img_2013](https://user-images.githubusercontent.com/36776420/52538587-565a7f00-2d6c-11e9-8724-eae509ecb26c.jpeg)
![img_2015](https://user-images.githubusercontent.com/36776420/52538589-59556f80-2d6c-11e9-9f3e-3fdaa663dda2.jpeg)

**Comment by ccrama** [comment]
I cannot find the app on the App Store to be able to find it's internal link tag. For example, firefox focus is firefox-focus://URL. If you are able to figure that out I can add support for Klar!

**Comment by colejd** [comment]
firefox-klar?

**Comment by ccrama** [comment]
I would need confirmation because we cannot test this in the US @colejd

**Comment by colejd** [comment]
https://en.m.wikipedia.org/wiki/Firefox_Focus

It looks to me like a separate branded version just for Germany.

**Comment by ccrama** [comment]
The issue is the url scheme is not the same as the normal firefox app, which Slide does support

**Comment by rm-rf-home** [comment]
It's probably "firefox-klar://". I found this after a lot of googling: [https://github.com/mozilla-lockbox/lockbox-ios/pull/547/commits/54e95b19a14e57191f3326c78742f5079ca703ce](https://github.com/mozilla-lockbox/lockbox-ios/pull/547/commits/54e95b19a14e57191f3326c78742f5079ca703ce)

**Comment by colejd** [comment]
;)

**Comment by rm-rf-home** [comment]
Is there a way for me to test it? I would love to help.

**Comment by colejd** [comment]
Try `firefox-klar://open-url?url=https://www.google.com`

**Comment by rm-rf-home** [comment]
Looks good, it opens google in Klar on my iPhone

**Comment by ccrama** [comment]
Added support in the next beta build! I cannot test this, so if it works please close the issue

**Comment by rm-rf-home** [comment]
Will do!

**Comment by ccrama** [comment]
Should be out now @rm-rf-home  :)

**Comment by rm-rf-home** [comment]
Works great, thank you!
