### ISSUE TITLE
Add a previously viewed post history

### ISSUE THREAD

**Issue by dheggers** [ccrama/Slide-iOS#773]
I think there should be a history feature that shows all previously viewed posts so it is easier to find a post you saw a while ago. Possibly similar to the one in the default reddit app. Also, a setting to toggle whether NSFW content should be saved to history would be nice.

**Comment by colejd** [comment]
Have a look in the History section of the settings. We have a toggle for this :)

**Comment by ccrama** [comment]
Merge with #1020
