### ISSUE TITLE
Improve text rendering

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#774]
There are a few text issues that have slipped through the cracks a bit that we could polish up.
- [ ] Nested quotes are unsupported
- [x] Newline after nested quotes isn't respected
Example:
    ```
    >>> Line 1
    Line 2
    ```
    will render as
    ```
    |
    |
    | Line 1 Line 2
    ```
- [x] ~~Nested superscript isn't supported~~
- [x] Inline code not supported
- [x] We can use `YYTextBorder` for code blocks instead of making separate items in the TextStackView for them. Should we?

**Comment by colejd** [comment]
It looks like DTCoreText supports superscript, but the baseline is only offset for text that is drawn using DTCoreTextLayoutFrame. We instead pass the attributed string into YYText. How can we detect superscript in YYText and display it properly?

**Comment by colejd** [comment]
From what I'm seeing, YYText does support superscript, but it isn't rendering it with the correct baseline. It also screws up pretty badly depending on the font. Unless we want to write our own text renderer we'll just have to settle for one level of superscript.

**Comment by ccrama** [comment]
I force superscript by doing <font size="1">, and remove all sup tags. I have found that text renderers are pretty terrible at this in iOS so I think overriding it is the way to go. As for the quotes, I tried that but there is no way to do a left-side border which I feel is the standard for a quote, so that method might not work well for us

**Comment by ccrama** [comment]
>  Newline after nested quotes isn't respected

Reddit is the one turning them into one blockquote, not Slide. We just parse the html

**Comment by ccrama** [comment]
All of these should be fixed now, except nested quotes. I feel that is niche enough to not warrant re-doing quote rendering
