### ISSUE TITLE
Crashing in given comment thread

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#779]
https://www.reddit.com/r/AskReddit/comments/aumhwo/which_conspiracy_theory_is_so_believable_that_it/eh9n8lr/?context=5

- [ ] If you open this link in Slide, and then hit "load full thread", you will get a crash.
- [ ] If you go to the full thread and hit “load `n` more”, as in loading more of the comment’s direct children, you will get a crash.

**Comment by ccrama** [comment]
I am not able to reproduce either of those issues

**Comment by colejd** [comment]
That's weird... now I can't either. Was it a specific comment that did it?
