### ISSUE TITLE
App crashes when going to comments with Roboto Bold font selected

### ISSUE THREAD

**Issue by medi0crescientist** [ccrama/Slide-iOS#78]

**Comment by ccrama** [comment]
Do other fonts work?

**Comment by medi0crescientist** [comment]
All other fonts seem to be working fine. I've only encountered this bug with Roboto Bold. I change the to that font then go to the comment section of a pos and it immediately crashes.

**Comment by ccrama** [comment]
Is this still ocurring? I cannot reproduce it anymore

**Comment by medi0crescientist** [comment]
Yes, it's still crashing when I go to comments with Roboto Bold selected.

**Comment by ccrama** [comment]
No longer reproducible, feel free to re-open if this still happens in Alpha 4
