### ISSUE TITLE
Auto-cache comment depth setting missing

### ISSUE THREAD

**Issue by mitchjhill** [ccrama/Slide-iOS#785]
Hi team - Either I'm going blind or there doesn't appear to be an option available to set a default comment depth for auto-cache.

Steps to reproduce:
1. Navigate to Settings -> Offline caching
2. Toggle 'Cache subreddits automatically' on
3. Toggle a text-based subreddit on
4. Wait for caching of subreddit/s to complete
5. Turn aeroplane mode on
6. Open a cached post
7. A banner message appears stating 'No cached comments found! You can set up auto-cache in Settings > Auto Cache'

This in combination with https://github.com/ccrama/Slide-iOS/issues/756 means that comments can only be loaded for an 'auto-cached' post (that hasn't been opened previously) by relaunching the app when data is available and opening the post again.

Side note; the banner message should be updated to read 'Settings > Offline caching' instead of 'Settings > Auto Cache'

**Comment by ccrama** [comment]
Good find, merging with #788 !
