### ISSUE TITLE
A few bugs with the post scores, image albums and lagged scrolling

### ISSUE THREAD

**Issue by Abstroos** [ccrama/Slide-iOS#79]
![img_0018](https://user-images.githubusercontent.com/20694935/28293307-55fbc7c6-6b08-11e7-8bc7-09967a829417.PNG)
![img_0020](https://user-images.githubusercontent.com/20694935/28293308-5607d7f0-6b08-11e7-8d90-26a553d26db1.jpg)
![img_0019](https://user-images.githubusercontent.com/20694935/28293309-560a6222-6b08-11e7-924b-ea0ca327540c.jpg)

As seen from the attached images:
- There is a blank space right after the clear history. Clicking that does the same thing as clearing history
- The scores were replicated when the toggle "Show scores below the title" is on
- In the data saving tab under settings, the last sentence text is not shown completely

Also when the "show hide button" is toggled on, it lays on top of the score/comments of the post. It was seen when I first opened the app and switched it on. I cannot replicate it again.
Also When a  user has only a few posts like 3 or 4, it repeatedly shows the same posts when you scroll.
The sidebar was very difficult to access. I had to like swipe more than 10 times to get to it.

Also, the following made the app to crash:
- Image album with larger files
- Come to the top of the subreddit page with a lot of images when you have scrolled a few pages down

I would also like to make a few requests (If possible):
1. Animate the upvote/downvote comments (as in narwhal)
2. Autoplay GIFs when scrolling
3. Option to save GIFs
4. Passcode protection
5. inline album viewer

I would be adding to these requests.

Thank you!!!

**Comment by ccrama** [comment]
Many of these have been fixed or implemented, if an issue still persists or you would like to make a feature request, please make a separate issue for each. Thank you for the feedback!
