### ISSUE TITLE
Content isn't getting loaded when clicking a comment that loads another post

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#815]
It'll open the VC, but it won't have anything in it. You can fix it by triggering a layout refresh, which I do by changing the sort order.

**Comment by ccrama** [comment]
That’s been fixed in 3.0.1 with the new refresh animation

**Comment by colejd** [comment]
I’ll pull just to make sure, but I believe this is happening to me on the latest build off of master.

**Comment by ccrama** [comment]
Fixed now, issue was transitioning in the content while the navigation push was transitioning as well
