### ISSUE TITLE
Subreddit header enhancements

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#817]
- [ ] Always start with header visible when visiting in Single mode (would be good for the new/visiting subreddit experience)
- [x] Make the above optional (default is on)
- [x] Add option to choose whether to start with the header visible in non-single mode (default would be off, which is the current behavior)
- [x] Add sidebar button
- [x] Add subscribe button
- [x] Add submit button

~~Should we move the sort button here too?~~

**Comment by ccrama** [comment]
I like all of those ideas! I think 1-3 could be replaced with just one selector, which would simplify it a bit. I don't think sort should go there just because the sort option is right next to it in the nav bar

**Comment by ccrama** [comment]
I'm splitting the first one into a new issue for a future release
