### ISSUE TITLE
Add option to choose how to show images from selftext posts

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#818]
If a self post contains a link, Reddit scrapes an image from it for us to show, which we display as a banner by default. This creates a lot of clutter at the top of subreddits, where pinned posts are typically self posts with links. I propose we add an option to choose how to display images in these situations, with the default being no image. 

The idea here is that it simplifies our (default) visual language -- if you see a banner image, it means you can click it to view it in the media modal. If you see a thumbnail, it means you're going to a website when you click it. If there's no image, you're always opening a subreddit when you click it.

**Comment by ccrama** [comment]
That exists in Settings > Comments already!

**Comment by colejd** [comment]
Where?

**Comment by ccrama** [comment]
Hmm, it was definitely an option at some point because I have them turned off. Wonder if it's getting cut out of a settings tableview somewhere?

**Comment by ccrama** [comment]
We have a setting value called "hideImageSelftext"

**Comment by ccrama** [comment]
Added an option to enable this and disabled it by default
