### ISSUE TITLE
Option to disable single-tap jumping to user profile / subreddit from post

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#824]
The amount of space to open comments is sometimes small and it’s hard to tap the right spot. Often times I end up going to a user profile or subreddit when I actually wanted to open the comments. 

It would be nice if there was an option to disable single click jumping to a user / subreddit - if I want to open a profile or jump to a subreddit I can still long press the post and choose the appropriate option from the pop-up menu.

**Comment by ccrama** [comment]
That is actually totally removed from the next update, as it was causing comment opening to "hang" in some places
