### ISSUE TITLE
App constantly crashing after opening, and after a few minutes of use 

### ISSUE THREAD

**Issue by rci27** [ccrama/Slide-iOS#825]
iPhone 7
iOS: 12.1.4
Slide 3.0.1 build 111

For the past few weeks Slide crashes at least half the time when opening.  When open, It will usually crash again.  I have tried cleaning the cache and history.  

When it crashes the app still runs in the background. Which means it will crash, then I still have to kill it in the background, and try launching again.

Any help is appreciated.

**Comment by colejd** [comment]
Does this persist if you reinstall the app?

I'm also a bit confused -- you mean that the app is unresponsive but doesn't close itself? So then you're killing the app and restarting it yourself?

**Comment by AquaStringBand** [comment]
Hi, I created a video capture: https://www.dropbox.com/s/94asg5x2lnwmgeh/Video%20Apr%2003%2C%208%2009%2051%20AM.mov?dl=0

Sequence of events:

- Launch app
- Browse/scroll
- Open first entry
- Open second entry (dank memes cartoon) CRASH
- However, when I go to look at apps running in the background Slide is still there - so not a full crash
- I did this two times in a row

This happens about 80% of the time with the remaining 20% being a stable experience.

**Comment by colejd** [comment]
This is very helpful, thank you. I’m going to see if I can reproduce this on my iPhone 7. I think this may have to do with memory constraints being hit @ccrama

**Comment by ccrama** [comment]
Memory would not cause the app to become unresponsive, have you tried reinstalling the app @AquaStringBand ?

**Comment by AquaStringBand** [comment]
I’ve reinstalled and I will report back. Thanks.

**Comment by ccrama** [comment]
Any updates?

**Comment by AquaStringBand** [comment]
So far the app is stable but I have not used it vigorously yet. I will have a better idea after the weekend.

**Comment by AquaStringBand** [comment]
Wanted to report back that stability is 99% better. Just 2-3 random crashes in the bast 2 weeks which I can’t replicate. Thanks.

**Comment by ccrama** [comment]
Glad to hear that! If you run into it again, let me know
