### ISSUE TITLE
[Feature Request] External Keyboard Support

### ISSUE THREAD

**Issue by moseylevy** [ccrama/Slide-iOS#842]
please add external keyboard support so we can navigate the app using the arrow keys.

**Comment by ccrama** [comment]
Done for v4.0!

**Comment by ccrama** [comment]
Also added some shortcut keys to common actions

**Comment by moseylevy** [comment]
Sweet!!

[Mosey Levy - Chat @ Spike](https://www.spikenow.com/?ref=spike-organic-signature&_ts=2zobl)	[2zobl]

On July 21, 2019 at 19:29 GMT, Carlos Crane <notifications@github.com> wrote:

Also added some shortcut keys to common actions
