### ISSUE TITLE
Crash on adding r/all to subscriptions, same with r/frontpage

### ISSUE THREAD

**Issue by Rozurenzu** [ccrama/Slide-iOS#843]

**Comment by ccrama** [comment]
Where are you subscribing to all?

**Comment by Rozurenzu** [comment]
Hello,

I'm getting the crash when I go into Settings>Subscriptions, tap the plus icon in the upper right, and click r/all. Hope that helps.

Best Regards,

Ty Duncan

**Comment by ccrama** [comment]
Should be fixed for v4.0!
