### ISSUE TITLE
Multitasking content not totally hidden after rotation

### ISSUE THREAD

**Issue by digitalqualms** [ccrama/Slide-iOS#847]
It looks like a black shade falls over the content but it doesn’t cover the bottom.

Pad Pro 11” iOS 12.3 (16F156)
Slide 3.1 Build 112

Swiping up but pausing:
![E3840B30-8795-4816-AFB1-9C94DBC7CFAC](https://user-images.githubusercontent.com/50979043/58305896-4583c580-7dbf-11e9-9987-3bce01b8abc4.jpeg)

Multitasking switcher card:
![57FF2C80-FAE7-4B0C-9528-4B273E3A6ED2](https://user-images.githubusercontent.com/50979043/58305505-f4270680-7dbd-11e9-87ed-5ca722777d18.jpeg)

**Comment by digitalqualms** [comment]
Actually, it happens in landscape as well. It appears to happen if you rotate while in the app and then switch. 

![BAC0AF2A-E1DE-41F1-B549-360B97FCA6B3](https://user-images.githubusercontent.com/50979043/58308056-1b81d180-7dc6-11e9-8b23-67b7d9c3cb04.png)

**Comment by ccrama** [comment]
Good find! Should be fixed now
