### ISSUE TITLE
Some comparison with Android version

### ISSUE THREAD

**Issue by slio** [ccrama/Slide-iOS#855]
Hi team,

Having some issues while transtioning from Android to iOS version - All these issues arise as I am a lurker and DO NOT want to login to reddit app.

Search
- I am not able to search without login  , on Android I can easily do that
NSFW subreddits
- Same issues, I can search the subreddits without login on adnroid, however not able to do so on iOS.

It could be a guest mode feature that may be missing on iOS. 
iOS 12.2
Slide version - 3.1 build 112 
I am on PRO subscription if that makes any difference to settings.

Android version - 7.1
Slide version - 6.2

Additional question - Is there any previous/old version of iOS i can enable the NSFW subreddits and save settings and then upgrade to latest version? I believe that must have happened in android version and that's why it allows me to browse in guest mode.

**Comment by colejd** [comment]
Unfortunately, that's just the way it has to be. We've had a long history with Apple rejecting Slide based on the ease of accessing NSFW content. They will not accept the app if the search function lists NSFW content without explicitly opting in on the website, which necessitates a login. They're so strict about it that we had to remove a button that _turns NSFW off if it's on_. Mentioning it at all is a problem. We've wasted about two months total of review time fighting this sort of issue.

That said, I believe you should be able to directly enter a subreddit and go to it when you're not logged in, regardless of content.

**Comment by slio** [comment]
Hi colejd,

Thank you for your reply, I understand the issue with NSFW. 
- I am not able to directly go to subreddit as it always ask me to accept Over18 pop-up. I tried logging with one aaccount and enable the content settings and save settings in slide app, however after logging out it still shows the same pop up

Regarding Search feature -> Slide doesn't let me search using 3 dot menu (Right side) -> Search
It always shows "Log in to search" You must be logged into Reddit to search -> Close
This behaviour is not seen in android app where in i can search all over reddit and within subreddits vi guest mode.
Does both API work differently?

PS: Other clients like Comet for Reddit : https://apps.apple.com/us/app/comet-for-reddit/id1146204813 can show the content like I have mentioned above, could you please have a look there how they are able to achieve this?

**Comment by ccrama** [comment]
It is not an API limitation, Apple has explicitly told me that we cannot have that feature while logged out. Comet has not been told the same apparently, but I risk getting banned if we added that feature back in.

**Comment by slio** [comment]
> 
> 
> It is not an API limitation, Apple has explicitly told me that we cannot have that feature while logged out. Comet has not been told the same apparently, but I risk getting banned if we added that feature back in.

Fair enough, could you please help me with search feature, so i can atleast search like we can in Android (without logging in)

**Comment by ccrama** [comment]
Apple will not allow me to have search when not logged in. Sorry :(
