### ISSUE TITLE
Popup video player: audio mutes on rotation

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#859]
This seems to happen on every video.  Here’s one I just tested with: https://reddit.com/r/funny/comments/cnt8no/best_cops_ever/

Steps to reproduce:
- open video in portrait orientation
- rotate device to landscape
- audio will stop until you close and reopen the video
- note: issue also occurs when going from landscape to portrait 

I’m using an iPad mini with the embedded video player.  All of the “popup video player” audio settings are set in the off position and the alerts on my device are muted.

**Comment by ccrama** [comment]
I believe this was fixed in v6, if not it definitely has been fixed in v7 (releasing this week, on TF now)
