### ISSUE TITLE
Incorrect post layout width after rotation

### ISSUE THREAD

**Issue by rebel1804** [ccrama/Slide-iOS#86]
The post layout width is incorrect after rotating after app is opened. Post layout is corrected when relaunching the app. iPhone SE IOS 11 Public Beta
![img_0034](https://user-images.githubusercontent.com/8388331/28304131-50c8d134-6b64-11e7-8e0a-d1252c93713f.PNG)
![img_0033 1](https://user-images.githubusercontent.com/8388331/28304164-725a40e4-6b64-11e7-972e-a15e3c34e236.PNG)

**Comment by ccrama** [comment]
Fixed
