### ISSUE TITLE
App Icons for Share and Reply are wrong

### ISSUE THREAD

**Issue by tehdef** [ccrama/Slide-iOS#866]
Using the new live release. 

When in a comment thread, the icon to share is the split triangle. This is wrong and not the share icon for Apple devices. 

When in a comment thread, the icon to reply is a hooked arrow. This is wrong.

When trying to POST a comment, the icon is the split sideways triangle. This is confusing, because it’s the same icon doing different things. 

[a version of share icon](https://cdn.onlinewebfonts.com/svg/img_523454.png)

Can you please update your icons to conform
With standards that iOS users are familiar with?

PS: please let me pad out the posts more, so there is additional space between the top, text, picture, buttons and bottom. It’s super cramped and really not great for readability.

**Comment by colejd** [comment]
Hello, I'm a bit confused. 

> When trying to POST a comment, the icon is the split sideways triangle. This is confusing, because it’s the same icon doing different things.

Could you please elaborate? I'm not sure where in the app you're seeing this, but the icon should be the hooked arrow for both replying to posts and replying to other commenters. This isn't necessarily "wrong"; to my knowledge Apple doesn't have a recommendation or precedent for the iconography in this case. I'll leave it to @ccrama for whether we should use a different icon. If you have a suggestion for a better icon I'd be happy to consider it. Personally I've advocated for [this one](https://material.io/resources/icons/?search=message&icon=message&style=baseline) in the past. 

For the share icon, I agree that we should be using the iconography Apple provides and users expect.

As an aside, neither of us are graphic designers so we've been going with [Material Icons](https://material.io/resources/icons). We are planning on overhauling all the iconography with [SF Symbols](https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/) in the near future.

**Comment by tehdef** [comment]
Hey Cole!

Thanks for poking in. I think “wrong” was unfair of me for the reply. I’ve had an android and the rely just never sat well with me. 

In this case I think the preferred choice is the “compose” icon, as you would be composing a reply. 

https://developer.apple.com/design/human-interface-guidelines/ios/images/icons/navigation_bar_toobar_icons/Navigation_Compose_2x.png

Or 

https://developer.apple.com/design/human-interface-guidelines/ios/images/icons/quick_action_icons/QuickActions_Compose_2x.png

But you’re right. You’re using the android icons, but I can tell you it’s super confusing and I would love to see edits to this. 

My suggestion to you is to make “icon packs” for android material, iOS human, and anything else that might come off as something to add to Pro to get some more money. 

I want you guys to make money which is why I’m a Pro buyer. But man, can we please get the priority of this bumped so that when iOS13 Launches not only do you have the right iconography, but you also have all the sweet new changes you guys made, resulting in a super cohesive experience within the Apple design language. 

Thanks!

**Comment by colejd** [comment]
For the padding thing, please make a new issue. That helps us stay organized :)

I plan on doing some major reworking of the iconography if Carlos doesn't do it first. In 4.0 we introduced a new context menu that closely follows iOS 13's design, so we definitely care about platform cohesion. SF symbols are going to be used throughout the app (approval pending).

**Comment by colejd** [comment]
Also, your feedback is very appreciated. Thank you for taking the time to articulate your feelings about the app. This helps us a lot!

**Comment by tehdef** [comment]
Hey Cole! thanks for taking the time again. One of the main reasons I switched was because your context menu changes. 

 I am a pretty avid UX fan. I’m an pro user for Slide and I also back the ultra level for Apollo and I talk shop with Christian. When I owned my Android phone I would talk with LJ for Reddit Sync, so I’ve been kind of around you might say for the Reddit app market and kind of discussing thoughts and ideas and feedback with the designers of those apps. Can always count on me to be someone that will sing praises for great design but also be critical and observational on the the app and that the details and minutia of user experience.

I’ll Create another thread about padding. Also, let me know if you can support more beta testers. I’d be happy to help.

**Comment by ccrama** [comment]
I have replaced all app icons with SFSymbols in iOS 13, which will use the Apple specified images. Interestingly, Apple now calls the hooked arrow "reply" and a paper plane "send", which is going to stick in the release version

**Comment by ccrama** [comment]
Although the icons themselves aren't changing, the design is due to SfSymbols, and I'd like to hear your feedback once v5 comes out @tehdef
