### ISSUE TITLE
Comments cut off with ellipses

### ISSUE THREAD

**Issue by muhammadahmad1220** [ccrama/Slide-iOS#870]
Comments text is often cutoff with ellipses at the end

Example:
![image](https://user-images.githubusercontent.com/15897883/64043968-b6134e80-cb33-11e9-885b-3702d15bfd5b.png)

**Comment by ccrama** [comment]
Do you happen to have the "thicker comment depth indicator" setting enabled in Settings > Comments? Thanks for the report!

**Comment by muhammadahmad1220** [comment]
Yes, I had that enabled. The issue goes away when that's not checked

**Comment by arcath-** [comment]
Thanks for the fix... this has been bugging me for weeks now.

**Comment by ccrama** [comment]
Merging with #890
