### ISSUE TITLE
App crashes when collapse comments by default enabled and you tap a top level comment with no replies

### ISSUE THREAD

**Issue by k3lsey** [ccrama/Slide-iOS#88]
When I tap a top level comment with no replies with collapse comments by default enabled, the app immediately crashes. It also occurs consistently. 

It doesn’t seem to happen when collapse comments by default is disabled.

**Comment by ccrama** [comment]
Does it show [0] comments in the little bubble on those replies without children? If so, I know where the issue is

**Comment by k3lsey** [comment]
No, it's on comments that have no bubble at all. I can long press without issue, but just a quick tap on a top level comment and it crashes.

**Comment by ccrama** [comment]
Fixed!
