### ISSUE TITLE
Video frame in cells doesn't match preview image frame

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#888]
For any cell representing a post with video, the video's frame doesn't match the preview image's frame. It's a little smaller. You can see seams on the left and right sides. We need to make changes to the video frame calculation to fix this.

**Comment by ccrama** [comment]
Note that it is *correct* with list mode. Issue is we are not accounting for card outside padding when calculating the height given the width

**Comment by colejd** [comment]
I think it runs deeper than that. The amount of inaccuracy seems to be different depending on the post.

**Comment by ccrama** [comment]
Fixed by setting the mode to aspectFill
