### ISSUE TITLE
YouTube videos can't be dismissed while buffering

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#889]
This one's a bit annoying when YouTube is acting up, which is nearly all the time. The loading spinner animation that displays during buffering blocks the user from dismissing the video.

**Comment by ccrama** [comment]
@PiwwowPants I believe this is fixed with your PR? #920

**Comment by PiwwowPants** [comment]
@ccrama possibly. The only things blocking the main thread now are mute/unmute, regrettably. Nothing ever blocked buffering explicitly though so maybe it got circumstantially resolved with some other action that was occurring. 

I will note that I’ve not been able to reproduce this even before my change. I think if @colejd could grab PR #920 to test that’d validate.

**Comment by ccrama** [comment]
This has been fixed by work by @PiwwowPants !
