### ISSUE TITLE
Flair addition in `titleForSubmission` is incorrectly executing on background thread

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#892]
The following line causes a runtime error since it's a UI call but it isn't being run on the main thread:

https://github.com/ccrama/Slide-iOS/blob/3d0d47da0c727b9ecc05278d08c8218e2d41df18/Slide%20for%20Reddit/CachedTitle.swift#L88

**Comment by ccrama** [comment]
Your PR fixed it in the list view, but the flair is gone in comments for some reason... I am thinking that it loads it into memory later for the CachedTitle class, and when the cell loads in the collectionView it is already present. In comments, it does a fresh title creation and instantly returns the NSAttributedString
