### ISSUE TITLE
Spoiler tags

### ISSUE THREAD

**Issue by loskristianos** [ccrama/Slide-iOS#90]
Spoiler tags in comments are not displayed correctly - comment shows ‘spoiler’ where tagged item should be but is not clickable to view spoiler text. 
E.g multiple tagged spoilers in the comment linked below:
http://reddit.com/r/discworld/comments/6m3zq2/rereading_raising_steam_spoilers/dk3osdv

**Comment by ccrama** [comment]
Done!
