### ISSUE TITLE
[Request] Swipe from right edge to open subreddit list, like clicking on the icon in the bottom-left.

### ISSUE THREAD

**Issue by ohkeepa** [ccrama/Slide-iOS#916]
I have submission gestures disabled, and so swiping from the right-edge to the left isn't used for anything. It would be awesome if that could open the subreddit list like clicking on the icon in the bottom-left.

This is how the app "Readder" works, and it's super-quick to jump from subreddit to subreddit that way. But, Readder isn't being actively developed and is currently somewhat broken on iOS 13.

**Comment by ccrama** [comment]
I will be extending this with more options. My thoughts are

- [ ] Inbox
- [ ] Subreddit list
- [ ] Open sub sidebar
- [ ] New post

Any other thoughts?

**Comment by ccrama** [comment]
Done for the next TF
