### ISSUE TITLE
[REQUEST] Fix URLs in messages so they can be opened

### ISSUE THREAD

**Issue by kilsey** [ccrama/Slide-iOS#921]
# User Story

As a Slide user, I would like to tap on a link in a message (personal inbox or moderation) and have it open so that I can view the content

# Current Behavior

When I receive a message in Reddit or view my moderation queue and tap on it in Slide, it automatically opens the reply state. This makes it difficult to open a link a friend has sent me, view a comment that Automoderator is flagging, or a post that a user has reported.

# Desired Behavior

When I tap on a link in a message (whether in my inbox or moderation), it functions similarly to a comment and opens in Slide (if Reddit link) or safari view controller (if any other site link). To get to a reply state, I'd either like to tap and hold (similar to getting to a reply state for a comment), or have a swipe action.

Separately, having some filtering/sorting options would be grand.

**Comment by ccrama** [comment]
This has been done in v7! Both in the inbox view, and threaded mail view.
