### ISSUE TITLE
Sidebar can’t be closed iOS 12

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide-iOS#946]

**Comment by rci27** [comment]
I would like to second this issue.  iPhone 7/ iOS 12.4.1 - when hitting the "i" button to view a sub sidebar there is no navigation button to return to the previous screen.  The only way to select the sidebar view is to close the app and reopen.  Normally, there is a left pointing arrow at the top - this is missing.  It appears on my other devices which have NOT upgraded to v5.

**Comment by ccrama** [comment]
Fixed!
