### ISSUE TITLE
Slide using large amount of storage

### ISSUE THREAD

**Issue by loganmarchione** [ccrama/Slide-iOS#947]
Recently updated to v5.0 and noticed this is still an issue. On my iPhone (iOS 13), Slide uses up a large amount of storage. The more I browse Reddit, the larger the storage grows.
![IMG_2011](https://user-images.githubusercontent.com/4955337/68779743-2b56d180-0603-11ea-9463-676865796805.PNG)

As you can see, I've cleared the cache. Any idea what's causing this?
![IMG_2012](https://user-images.githubusercontent.com/4955337/68779784-36a9fd00-0603-11ea-985f-1115806fac14.PNG)

**Comment by ccrama** [comment]
That is very strange. So Slide is showing no space taken and your phone is saying 35 gb?

**Comment by loganmarchione** [comment]
Yep, yesterday it was at 34.35GB, today it's at 35.31GB. Does yours do this? Is there any kind of log I can send you from Slide?

**Comment by ccrama** [comment]
Mine does not do this, I'm currently sitting at around 400mb which is expected with a few weeks of photos/cached comments. If Slide is reporting the low number then there is some sort of file within Slide's data that is not actually being tracked by Slide (not a cache file that is currently being written to). How long have you had Slide installed/used?

**Comment by loganmarchione** [comment]
Since December 2018. Should I uninstall and re-install?

**Comment by ccrama** [comment]
I think that is the only solution, let me know if it begins to grow that big again! Will leave this issue open for further discussion

**Comment by loganmarchione** [comment]
Closing this, it's been 5 days and it's only using ~400Mb. Sorry that I didn't try to uninstall/reinstall first!
