### ISSUE TITLE
Pro Regressions

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide-iOS#948]
- [x] Multi-column is default for iPad, but can't be switched back to if you switch out of it
- [x] Gallery mode disappeared in the bottom FAB menu
- [x] Auto night mode should not be pro in iOS 13

**Comment by PiwwowPants** [comment]
Should auto night mode not be pro at all anymore? If iOS 13 provides the functionality, would it make sense to make someone pay for it on iOS 12 only to receive it free for iOS 13?
Yes is an appropriate answer.

**Comment by colejd** [comment]
Yes is the only answer. App Store guidelines forbid charging for dark mode.

**Comment by colejd** [comment]
I misread. But yeah we shouldn’t charge at all.

**Comment by ccrama** [comment]
Done, done, and done. Now multi-column is free (and defaulted on iPad), and setting the number of cells is the pro part
