### ISSUE TITLE
Some YouTube files are not included in the Git repo, but are needed to display YouTube content

### ISSUE THREAD

**Issue by OrionDB5** [ccrama/Slide-iOS#95]

**Comment by ccrama** [comment]
Which files were you seeing were missing when you try to compile?

**Comment by OrionDB5** [comment]
YTPlayerView.h and YTPlayerView.m
When I cloned the repo the path of those two files was set to ../../../Downloads/[username]/youtube-ios-player-helper/Classes/

**Comment by ccrama** [comment]
Fixed this a little bit ago, forgot to close!
