### ISSUE TITLE
Dead zone when swiping between subreddits 

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#957]
When trying to swipe to the next subreddit, the right side of the screen has about a quarter inch of dead space.  If the swipe is initiated from the dead zone nothing happens.  I would expect that swiping would always navigate between subreddits - even if the swipe is initiated from off of the screen - when that functionality is enabled.

**Comment by ccrama** [comment]
Do you have the side gestures option turned on? That would make sense as the gesture is on the right side of the screen

**Comment by WickedColdfront** [comment]
That was my first thought too, but I think the side gestures are disabled. Let me know if I should be looking somewhere else. 

![C8234CB7-5AEC-4F25-AC47-16C653845F69](https://user-images.githubusercontent.com/26832587/69201192-b3a10f00-0afa-11ea-8026-71308b65e6b2.png)

**Comment by ccrama** [comment]
I believe this was fixed a while back in v6
