### ISSUE TITLE
Issues with videos from v.reddit.com

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#958]
Some videos from v.reddit.com have a black thumbnail and load to a black screen with audio.  Seeking back to the beginning of the video fixes the issue for the duration of the video. 

I’m experiencing the issue on an iPad Mini with 2 column view. I was unable to reproduce on my iPhone 11 Pro.  Tried clearing cache and restarting Slide. 

This is one video with the issue; I’ve noticed it on several others. https://reddit.com/r/aviation/comments/dwkse7/british_airways_a380_enters_hong_kong/

**Comment by ccrama** [comment]
I actually believe this is a Reddit issue, unfortunately. Looking at the JSON and trying to view the preview image results in a broken link

**Comment by WickedColdfront** [comment]
I should’ve posted this earlier - sorry for the delay!

Shortly after submitting the issue I rebooted my iPad and the problem went away. Not sure if the issue was related to Slide or iOS, but all is good now.

**Comment by ccrama** [comment]
Thanks for the update! If it comes back, please post again
