### ISSUE TITLE
Edit search in subreddit bug

### ISSUE THREAD

**Issue by Rknegt** [ccrama/Slide-iOS#959]
### How to reproduce
Search for something that isn't found using the subreddit search. Then edit your search and search for something that can be found on the subreddit. 

### The problem
When you do the second search in the background you can still see: "Nothing to see here!" while the search results go over that screen. You cannot scroll past the initial results and you cannot click on any of the results.

### Video of the bug
[https://imgur.com/a/DmcXQ6z](url)

**Comment by ccrama** [comment]
Good find! Fixed for 5.1
