### ISSUE TITLE
image haptic doesn’t include a save option

### ISSUE THREAD

**Issue by Human1895** [ccrama/Slide-iOS#963]
As someone who just came from Apollo this is one of the only differences that bothers me. In Slide the haptic doesn’t look like it does elsewhere in iOS and doesn’t include a save button (annoying for users that use gestures over buttons and have buttons disabled) I would try and fix this myself but I don’t know swift
![i](https://user-images.githubusercontent.com/29240729/70097573-b1a97680-15f7-11ea-928b-046b09467d8d.jpeg)
![87F432EB-37C5-4A7E-81A2-74201EC5880B](https://user-images.githubusercontent.com/29240729/70097706-02b96a80-15f8-11ea-94ca-83eb86609a7a.jpeg)
![F7CD2586-894E-4CB1-A91A-4E27D1CC161F](https://user-images.githubusercontent.com/29240729/70097707-02b96a80-15f8-11ea-8c01-52a6797a4c51.jpeg)

**Comment by ccrama** [comment]
Done for 5.1!
