### ISSUE TITLE
[Bug] Gallery view causes app to crash

### ISSUE THREAD

**Issue by Rknegt** [ccrama/Slide-iOS#971]
Update:
- Saw that the reason is already found. [Link](https://www.reddit.com/r/slide_ios/comments/eb1qoa/v51_changelog/fb5rcfe/?context=3)
And indeed when enabling the bottom bar it worked again.
- **Thread can be closed.**
------------------------------
The app crashes if you select gallery mode for a subreddit. Afterwards you cannot go to that subreddit again because it immediately crashes when it is opened.

If have attached two crash reports of the problem. 

- Slide for Reddit-2019-12-18-161354.ips -- When swiping through the subreddits and opening a subreddit that I tried gallery mode on and the app crashes.
- Slide for Reddit-2019-12-18-161412.ips -- When searching a subreddit where I tried gallery mode and the app crashes.

[SlideBugReport.zip](https://github.com/ccrama/Slide-iOS/files/3979087/SlideBugReport.zip)

[Link](https://www.reddit.com/r/slide_ios/comments/eb6xd9/bug_gallery_view_causes_app_to_crash/) to the reddit post. There is some more info there.

**Comment by ccrama** [comment]
Thank you for the detailed report! Reports like these are very helpful :)

It's fixed in v5.1.1 which is out now
