### ISSUE TITLE
Can’t add additional reddit accounts.

### ISSUE THREAD

**Issue by geancka** [ccrama/Slide-iOS#973]
I’m trying to add a second reddit account so i can switch between them. I get the login pop up screen from reddit, i login, then nothing happens when i go back into Slide. No new account.

I’m on a 2018 iPad Pro.

**Comment by ccrama** [comment]
When you complete adding the account (when you give Slide permissions), is it popping you out of Slide? Everything should be handled in app

**Comment by geancka** [comment]
Not sure why but it fixed itself after repeated attempts.

**Comment by ccrama** [comment]
If you notice this again, please re-open the issue!
