### ISSUE TITLE
[Bugs] Subscription list issues

### ISSUE THREAD

**Issue by Rknegt** [ccrama/Slide-iOS#974]
Issues found:
- [ ] In settings - subscriptions. When you remove the second (X-th) sub from pinned subscription, the second (X-th)  sub from all subreddits gets removed.  [Video 0.00](https://youtu.be/e_bwgEkfvj0). 
Thus as a result you can't remove a subreddit before unpinning.
- [ ] When you pin the same subreddit multiple times some weird things happen in the home view when swiping between subreddits. [Video 0.16](https://youtu.be/e_bwgEkfvj0?t=16)

**Comment by ccrama** [comment]
I believe #981 will solve these issues!

**Comment by Rknegt** [comment]
That would be awesome! Thanks @ccrama and @robertfalconer !
