### ISSUE TITLE
Slide crashes when sharing link on split mode

### ISSUE THREAD

**Issue by the-jame** [ccrama/Slide-iOS#979]
When opening the submission options and clicking share content or Reddit link- When the iOS menu opens the app becomes unresponsive and must be force closed.  
Content is in landscape mode. 

iPadOS 13.3

**Comment by WickedColdfront** [comment]
I’m having the same problem on an iPad mini. I have my view set to 2 columns, but I’m not using split mode. The problem happens from both the post screen as well as when trying to share from within a post.

**Comment by ccrama** [comment]
@the-jame @WickedColdfront I believe this is fixed in build 138. Can you confirm you are still running into this?
