### ISSUE TITLE
Tapping url preview bar does not open link in comments view

### ISSUE THREAD

**Issue by lnkcrb82r3z2g4** [ccrama/Slide-iOS#98]
In comments view, tapping the preview image will open a link but tapping the content type and url preview does not do anything.

**Comment by ccrama** [comment]
That is intended, I don't know if it would be possible to do that as the preview text is not part of the URL (in order to not have it underlined or bolded)

**Comment by lnkcrb82r3z2g4** [comment]
Just to clarify, I am talking about the area highlighted in red. On the Android Slide, tapping that area will open the link.
![dfogoe8voaa0eyy](https://user-images.githubusercontent.com/3632173/28601401-de99e918-716c-11e7-8cc8-5e8828a0211d.jpg)

**Comment by ccrama** [comment]
Oh we were on very different pages haha. Yeah will look into that

**Comment by ccrama** [comment]
Fixed!
