### ISSUE TITLE
No way to exit search on iPad 

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#982]
After clicking search while in a post there is no way to exit the search screen.  You can exit by swiping the post, but returning to the post without closing Slide results in the same search screen showing up. 
![DF35984F-3C07-427F-BD17-BD88D3A484A5](https://user-images.githubusercontent.com/26832587/72952605-9fbe9700-3d4f-11ea-851c-16bb76fa0280.png)

**Comment by personman** [comment]
@WickedColdfront Thanks for reporting this and documenting it clearly. I've submitted a pull request with a fix. It's my first PR with this project, so I have no idea if or when it might be accepted.
