### ISSUE TITLE
Request: Option to hide or streamline post/comment awards 

### ISSUE THREAD

**Issue by WickedColdfront** [ccrama/Slide-iOS#990]
The new Reddit award system is out of hand. Sometimes there are so many awards that they wrap to a new line. And I’m pretty sure I’ve seen some that are even animated. 

If possible it would be nice if there were an option to either hide them all or only show a total count (similar to how gold used to be).

**Comment by ccrama** [comment]
I like this idea, it's getting pretty ridiculous and only serves to make Reddit money
