### ISSUE TITLE
Video downloads show permissions error, even if permissions are granted

### ISSUE THREAD

**Issue by scot-onet** [ccrama/Slide-iOS#991]
Go to a video, tap on the download button. A red banner at the top will state an error occurred and ask if it has permissions to photos. 

Even though it does have permissions it does not work. Others are reporting the issue on reddit. 

Slide has been deleted and reinstalled.  No change in behavior.

**Comment by ccrama** [comment]
I think the issue was related to v.redd.it videos, I've fixed it for the next update!
