### ISSUE TITLE
Sorting requester color scheme

### ISSUE THREAD

**Issue by schack-lindemann** [ccrama/Slide-iOS#993]
If i’m using one of the Amoled themes the sorting requester color scheme is black text on black background. 

![Screenshot 2020-02-28 at 21 11 06](https://user-images.githubusercontent.com/17122463/75584606-6248da00-5a70-11ea-8681-20215979943d.png)

**Comment by ccrama** [comment]
Are you using a custom theme, or one of the built in themes? I am not able to reproduce

**Comment by schack-lindemann** [comment]
Standard AMOLED Black with Contrast as night theme. Night Mode follows iOS Dark Mode. Phone is 11 Pro running 13.3.1. Slide is latest App Store version 5.1.2 build 139. 
![IMG_0098](https://user-images.githubusercontent.com/17122463/76152717-27275600-60c3-11ea-9656-6d4340f76f8c.png)

**Comment by schack-lindemann** [comment]
I solved it. Reinstalled the app and set the theme again, this time without the problem.
