### ISSUE TITLE
Repeated crashes with gifs.

### ISSUE THREAD

**Issue by ElectricCharlie** [ccrama/Slide-iOS#998]
Currently a [specific post](https://www.reddit.com/r/interestingasfuck/comments/fcu3gz/if_a_box_does_not_quite_fit_you_may_be_able_to/)  is at the top of r/all and r/popular. 
Even though I have gifs set to not auto-load when on cellular, it is auto-loading anyway. I still get a screen over the gif with a “play gif” button in Safari, which is very odd. (I say that because Imgur might be doing something to force auto play.)
Even more pressing, every time this gif loads, Slide crashes. 
This post is at the top of r/all and r/popular right now, which makes most of what I browse on reddit completely unusable right now. Even just swiping across to try to get to a different subreddit is enough to freeze Slide until it crashes.

**Comment by ccrama** [comment]
I've traced the issue down to Reddit providing me a "thumbnail image" that is actually a 50mb .gif. When expanded into RAM, this is 5 gigabytes and instantly crashes Slide. Will have to look at a way to make sure Reddit is giving me the files it says it is..

**Comment by ccrama** [comment]
Fixed with 2b8ff8cb308f775fffcb3ebceb39fd74735a92ff
